### ISSUE TITLE
Using negative Tp values to investigate time delays

### ISSUE THREAD

**Issue by 4rachelgreen** [SugiharaLab/pyEDM#10]
Hello, 
I am trying to replicate this example of quantifying time delays in causation from rEDM into pyEDM https://ha0ye.github.io/rEDM/articles/rEDM-time-delay-ccm.html
However, I am getting errors in using negative Tp values.
`Parameters::Validate(): Tp must be positive.`
Is it possible to allow negative Tp values?

**Comment by nonlinearnature** [comment]
Hi Rachel- Thank you for bringing this to our attention. This should be possible, so we will investigate quickly.

**Comment by nonlinearnature** [comment]
Rachel can you please clarify which version of pyEDM you are using, as well as which specific function call is giving you that error?

**Comment by 4rachelgreen** [comment]
I'm using version 1.2.0.0  and the ccm function.

**Comment by nonlinearnature** [comment]
Ah! If you update to the latest version (from the github or pyPI) you should be able to set a negative Tp in ccm().
