### ISSUE TITLE
error upon import `undefined symbol: _gfortran_transfer_integer_write`

### ISSUE THREAD

**Issue by manihamidi** [SugiharaLab/pyEDM#12]
Hi there, 

I've successfully installed pyEDM but get this error upon importing the library (see below). I'm on a Ubuntu 20.04. 

Couldn't find anything useful on Google, was hoping you'd be able to help. 

Thanks,

```python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyEDM
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-de820d94157e> in <module>
----> 1 import pyEDM

~/PycharmProjects/pyEDM/pyEDM/__init__.py in <module>
      3 # import all EDM functions
      4 
----> 5 from pyEDM.CoreEDM import *
      6 from pyEDM.AuxFunc import *
      7 

~/PycharmProjects/pyEDM/pyEDM/CoreEDM.py in <module>
      5 from matplotlib.pyplot import show, axhline
      6 
----> 7 import pyBindEDM
      8 import pyEDM.AuxFunc
      9 

ImportError: /home/code/pyEDM/pyBindEDM.cpython-38-x86_64-linux-gnu.so: undefined symbol: _gfortran_transfer_integer_write
```

**Comment by SoftwareLiteracy** [comment]
Looks like your system does not have gfortran installed?  

If not, `sudo apt install gfortran`. 

This is from an Ubuntu 20.04 machine:
```
~> locate gfortran.a
/usr/lib/gcc/x86_64-linux-gnu/9/libgfortran.a
~> nm -a /usr/lib/gcc/x86_64-linux-gnu/9/libgfortran.a | grep transfer_integer_write
0000000000000000 T _gfortran_transfer_integer_write
0000000000000000 t .text._gfortran_transfer_integer_write
```

**Comment by manihamidi** [comment]
Thanks for the quick reply. 

I definitely have gfortran installed, as I just had to install it to be able to install `lapack`. 

I also have `libgfortran.a` in the same directory as yours, and I get the following with your second command: 

```
$ nm -a /usr/lib/gcc/x86_64-linux-gnu/9/libgfortran.a | grep transfer_integer_write
0000000000000000 T _gfortran_transfer_integer_write
0000000000000000 t .text._gfortran_transfer_integer_write
nm: c99_functions.o: no symbols
nm: atomic.o: no symbols
```

... which is consistent with the first two lines in your output.

I wonder if the comment [here](https://www.reddit.com/r/archlinux/comments/4pai1a/gcc6_and_libgfortran_where_is_libgfortrana/) may be relevant? 

```
I asked in #archlinux irc and Namarrgon had the answer: Apparently in Arch static libraries are being removed if they have a .so counterpart. That's the general policy with Arch and /etc/makepkg.conf actually contains the default option !staticlibs. So what I need to do is recompile gcc-fortran with option=('staticlibs').
```

thanks for your time...

**Comment by manihamidi** [comment]
Ok, I just tried the vanilla installation using pip and prebuilt binaries on pypi and I don't get the error any more! 

Shouldn't have bothered with the manual install in the first place...  still curious what the issue was with the manual install, if anyone here figures it out. 

Thanks.

**Comment by SoftwareLiteracy** [comment]
I always manually build pyEDM and test it on Ubuntu. This seems to be an import/runtime error, not a build error?

The pyBindEDM module is the main interface between the C++ core and pybind11.  I wonder if running from within IPython makes a difference, as the problem seems to be failure to load/locate a .so.  Some kind of environment/path difference.  I have seen things like this before using IPython on compiled modules.

**Comment by manihamidi** [comment]
hmm... I doubt it's an IPython issue, I get the same error when I just import from the python console.
