### ISSUE TITLE
CCM parameter clarification 

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#14]
There is an example of implementing CCM provided in the pyEDM documentation (https://sugiharalab.github.io/EDM_Documentation/algorithms_high_level/)  : 

```
pyEDM.CCM( dataFrame = sardine_anchovy_sst, E=3, columns="anchovy", target="np_sst",
           libSizes  = "10 70 10", showPlot=True, sample=100);
```

Can you clarify what the `libSizes` argument corresponds to in this example? Also how is the value for the`sample` argument is chosen? Thank you!

**Comment by SoftwareLiteracy** [comment]
As mentioned in the [docs](https://sugiharalab.github.io/EDM_Documentation/edm_functions/#ccm): `libSizes` specifies a string of whitespace or comma separated library sizes. If the string has 3 values, and, if the third value is less than the second value, then the three values are interpreted as a sequence generator specifying "start stop increment" row values, i.e. "10 80 10" will evaluate library sizes from 10 to 80 in increments of 10.

In the example you provided: `libSizes  = "10 70 10"` the sequence of library sizes is 10, 20, 30, 40, 50, 60, 70.  A sequence starting at 10, ending at 70, and incremented by 10.  

`sample` defines the ensemble size of random embeddings at each libSize.  `sample = 100` will average results from 100 random embeddings (samples from the library) at each libSize.  100 samples seems to provide a reasonable balance between run time and stable variance of the correlation coefficent.  Smaller values will run faster, larger values will provide more stable estimates.  This is data dependent. 

For a complete understanding, please see:
Sugihara G., May R., Ye H., Hsieh C., Deyle E., Fogarty M., Munch S., 2012. Detecting Causality in Complex Ecosystems. Science 338:496-500.

**Comment by pshankinclarke** [comment]
Thank you!
