### ISSUE TITLE
Minimum CCM library length

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#19]
Is there  a minimum library length for CCM?

**Comment by SoftwareLiteracy** [comment]
CCM uses all available data for the library.  

In regards to the `libSizes` argument that form subsets of the library:
There are two hard limits:  
1) libSizes_min < E
2) libSizes_min < 3

Practically, very small library sizes (data record lengths) don't make much sense.  It is of course problem/data dependent.  Convergence as library size increases, presumably with sufficient information states to fully describe the dynamics, is inherent in CCM.  This is discussed in the [reference](https://science.sciencemag.org/content/338/6106/496).

**Comment by pshankinclarke** [comment]
Thank you!
