### ISSUE TITLE
CCM runtime error

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#20]
I'm running CCM with a 125 x 3 dataframe. For `libSizes` I'm using` "E + 1 125 1"`, but I'm getting the error : 

`CrossMap(): libSize=121 must be less than N_row=121 for random sample without replacement.`

If I change the increment to 6, then CCM will run again. Is there a formula I can use in order to calculate the minimum increment (i..e maximum number of points in a library) that I can use in a dataset for EDM? Thank you!

**Comment by pshankinclarke** [comment]
Thank you that was very clarifying

**Comment by pshankinclarke** [comment]
Sorry to reopen this issue, but I have a follow up question. For a dataframe with 100 rows and an E = 2, the maximum for libSizes must be less than 97 ( i.e. < N - (E + 1) = 100 - (2 + 1) = 97). I was testing this formula using `pyEDM==1.7.5.0` with a variation of an example provided in the pyEDM documentation (https://sugiharalab.github.io/EDM_Documentation/algorithms_high_level/)  : 
```
import pyEDM
sardine_anchovy_sst = pyEDM.sampleData['sardine_anchovy_sst']
df = pyEDM.CCM( dataFrame = sardine_anchovy_sst, E=3, columns="anchovy", target="np_sst",
           libSizes  = "4 78 1", showPlot=False, sample=100);
```
sardine_anchovy_sst has 78 rows : 

```
sardine_anchovy_sst = pyEDM.sampleData['sardine_anchovy_sst']
print(sardine_anchovy_sst.shape[0])
```

```
(env) parkers-MacBook-Pro:~ parkershankin$ python3 CCM.py 
78
```
 so the maximum number of rows must be less than N - (E + 1) = 78 - (3 + 1) = 74. But the error is  : 
```
Traceback (most recent call last):
  File "CCM.py", line 4, in <module>
    df = pyEDM.CCM( dataFrame = sardine_anchovy_sst, E=3, columns="anchovy", target="np_sst",
  File "/Users/parkershankin/env/lib/python3.8/site-packages/pyEDM/CoreEDM.py", line 350, in CCM
    D = pyBindEDM.CCM( pathIn,
RuntimeError: CrossMap(): libSize=76 must be less than N_row=76 for random sample without replacement.
```
It doesn't seem like the error matches the formula since it says that libSize must be less than 76 not 74.

**Comment by SoftwareLiteracy** [comment]
Thank you!

I agree that the error message does not match the formula.  I'll add this to the fix list for a future release.

**Comment by pshankinclarke** [comment]
Great thanks!
