### ISSUE TITLE
Simplex projection, columns not found error 

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#21]
I am using` pyEDM==1.7.5.0` and trying to run a simplex projection on the dataframe : 

df0 = 
```
     Time  T(t-0)
0       0   112.0
1       1    34.0
2       2    91.0
3       3    32.0
4       4   126.0
..    ...     ...
141   141   122.0
142   142   173.0
143   143   144.0
144   144   131.0
145   145   199.0
```
with the function : 
```
              df = pyEDM.Simplex(dataFrame = df0,
                                lib = str(1) + " " + str(100),
                                pred = str(105) + " " + str(140),
                                E = 2,
                                target = 'T(t-0)',
                                embedded = True) #make sure edm knows the data is already embedded
```
This gives the error : 
`RuntimeError: Parameters::Validate(): Simplex/CCM:  No valid columns found.`
 
I'm confused why this error is arising since the I have a properly labeled "Time" column and specify the target column.

**Comment by SoftwareLiteracy** [comment]
The `columns` parameter is required.  

Please note that when using `embedded = True`, that `E` is set to the number of `columns`, you do not need to specify it.

**Comment by pshankinclarke** [comment]
I changed the function in order to specify the default argument for `columns` (i.e.` columns = ""`) and I received the same error. However when I changed the argument to  `columns = 'T(t-0)' `the code ran successfully. Can you explain the purpose of the `columns` argument? Up until this point, I thought of it as the place to include non-target, non-time columns (e.g. some environmental variable W(t - 0)).

**Comment by SoftwareLiteracy** [comment]
As noted in the [documentation](https://sugiharalab.github.io/EDM_Documentation/parameters/):

columns | String or vector of column name(s) in the input data used to create the library. String names must be whitespace separated.

It is required in all EDM functions that make projections. As is `target`.

**Comment by pshankinclarke** [comment]
Thanks for your response. For clarification, if I want to use`Simplex()` in order to make a multivariate forecast with an already embedded target (T(t -0)) and environmental variable(W(t-0)) is this the correct formulation : 

```
              df = pyEDM.Simplex(dataFrame = df0,
                                lib = str(1) + " " + str(100),
                                pred = str(105) + " " + str(140),
                                E = 2, # E is set to the number of columns
                                target = 'T(t-0)',
                                columns = 'T(t-0) W(t-0)'
                                embedded = True) #make sure edm knows the data is already embedded
```

**Comment by SoftwareLiteracy** [comment]
That looks good. 

Note that the `lib` and `pred` arguments can be numeric lists or tuples.  `columns` can also be a list:
```
>>> df.head()
   Time  x(t-0)  x(t-1)  y(t-0)  y(t-1)
0     0  0.0631  0.0000  0.9980  1.0000
1     1  0.1260  0.0631  0.9920  0.9980
2     2  0.1883  0.1260  0.9821  0.9920

s = Simplex( dataFrame = df, 
             lib       = [1,100], 
             pred      = [101,110], 
             target    = 'x(t-1)', 
             columns   = ['x(t-0)','y(t-1)'], 
             embedded  = True )
```

**Comment by pshankinclarke** [comment]
Great, thanks for the tip.
