### ISSUE TITLE
Parameters::Validate(): Combination of E = 2 Tp = 1 tau = -1 is invalid.

### ISSUE THREAD

**Issue by SteinPanyu** [SugiharaLab/pyEDM#22]
Hello,
When I run EmbedDimension() and Simplex(), I got this kind of error. I set the library to be 70% of data. The length of dataframe is 20. 
![Capture](https://user-images.githubusercontent.com/80038088/114798608-af048700-9dd0-11eb-810d-1e657ac98de9.JPG)

If possible, could you give me any hint on that? 
Best regards and many thanks

**Comment by SoftwareLiteracy** [comment]
Please report the version.
```
>>> from pyEDM import *
>>> pyEDM.__version__
'1.8.1.0'
```
The head of your dataFrame would also be helpful.  It is assumed that the first column of the dataFrame is a time vector that is not used in `columns` or `target`.

**Comment by SteinPanyu** [comment]
Thanks for your propmt reply. I found the error and question solved:-) I set the lib as a list as in rEDM...It should be a string like "1 20" in pyEDM:-)

**Comment by SoftwareLiteracy** [comment]
Hmm... in pyEDM `lib` and `pred` can be a python list:
```
>>> type([1,14])
<class 'list'>
>>> Simplex( dataFrame = sampleData['circle'].iloc[0:20], lib = [1, 14], pred = [15, 20], columns = 'x', E = 2 )
  Time  Observations  Predictions  Pred_Variance
0   15        0.7733          NaN            NaN
1   16        0.8118     0.702560       0.001188
2   17        0.8470     0.697856       0.001290
3   18        0.8789     0.695402       0.001330
```

**Comment by SteinPanyu** [comment]
I see. I think I may make the wrong list... I try to mimic c function in r and made the wrong input I guess:-) Anyway, thank you for your reply!

**Comment by SteinPanyu** [comment]
Btw, could you give any hint on surrogate data generation based on this library? I didn't find the exact function to generate the surrogate data for causal effect significance check in CCM. Any help would be appreciated.

**Comment by SoftwareLiteracy** [comment]
The SurrogateData function is not implemented in pyEDM.  It is in rEDM, purely in R.  I'll add this to the development task list for pyEDM.  

If you want to see it in rEDM (it's a bit messy) you can look at the [SurrogateData function in R](https://github.com/SugiharaLab/rEDM/blob/master/R/EDM_AuxFuncs.R). It's at the bottom of the file.

**Comment by SteinPanyu** [comment]
I see. Thank you!

**Comment by SteinPanyu** [comment]
Hello, bro, could you transform that function to python if possible? It is a bit hard for me to rewrite th R code in python.:-)

Best regards and many thanks,
ZHANG Panyu

**Comment by SteinPanyu** [comment]
Thank you anyway:-) 
I will try to rewrite. If there is any update on the python surrogate function, plz reply in this post so that I can get notified about the up-to-date version. Thanks!

**Comment by SoftwareLiteracy** [comment]
If you do.,.. please share it!  I'm taking a crack at-it, but, my time is limited.  It will probably be a week or-so.

Thanks.

**Comment by SteinPanyu** [comment]
As for surrogate data generation, actually I refer to this blog. It is in japanese but I think you can use the google transalte add-on in chrome to read the blog. https://khigashi1987.github.io/pyEDM_Maizuru/
Btw, I am quite confused if we can compare the convergence level of CCM with cross correlation between variables. Say if convergence of prediction skill is above cross correlation, causal effect is significant. I just screenshot the below image from the rEDM documentation website.
![Capture](https://user-images.githubusercontent.com/80038088/115863260-2e005c00-a470-11eb-8395-bb49556eccf3.JPG)

**Comment by SoftwareLiteracy** [comment]
Thanks for the surrogate data link.  I'm working on the python implementation (as time allows). 

"if convergence of prediction skill is above cross correlation, causal effect is significant."

-- No.  There are several distinct questions here.

1) Is there a causal link?  
If CCM demonstrates convegence as the library size increases, that is evidence of a causal link.

2) Is the CCM inferred link significant?
That is the function of the surrogate test.  Are the surrogate CCM values significantly different than those from the data?  (For this to work, seasonality and other correlative cycles need to be addresed.)

3) Is the (terminal) CCM value greater than linear correlation?
This is viewed by some as a measure of non-linearity.  Personally, I find this to be a Type III error since linear correlation can over/underpredict when the data are not linear.

**Comment by SteinPanyu** [comment]
I see. Thanks for your answer!

**Comment by SoftwareLiteracy** [comment]
Here's what I have for a `SurrogateData` function.  I plan on adding this to pyEDM.

This code is a standalone application that reads a .csv file.  For example if the entire code is saved into the file `SurrogateData.py` with execute permissions, then:
```
./SurrogateData.py -i circle.csv -m ebisuzaki -n 5 -c x -p
```

```
#! /usr/bin/env python3

import argparse

from math   import floor, pi, sqrt, cos
from cmath  import exp
from random import sample, uniform, normalvariate

from pandas            import DataFrame, read_csv
from numpy             import mean, std, fft, arange, zeros, ptp
from scipy.interpolate import UnivariateSpline
from matplotlib        import pyplot as plt

#----------------------------------------------------------------------------
# Main function
#----------------------------------------------------------------------------
def main():
    '''Implement SurrogateData function for pyEDM.
       It is presumed that the input data file (.csv) has a time column
       (first column) that is propagated to the output. 
    '''
    
    args = ParseCmdLine()
    
    SurrogateData( args )

#----------------------------------------------------------------------------
def SurrogateData( args ):

    # Read in file
    df = read_csv( args.inputFile )
    
    print( "\n%d lines read from %s" % (df.shape[0], args.inputFile) )

    if args.method == "random_shuffle" :
        dfOut = RandomShuffle( df, args )
    elif args.method == "ebisuzaki" :
        dfOut = Ebisuzaki( df, args )
    elif args.method == "seasonal" :
        dfOut = Seasonal( df, args )
    else :
        raise Exception( "Invalid Data generation method." )

    dfOut = dfOut.round( 6 ) # Should be a parameter

    # Rename columns
    columnNames = [ args.column + "_" + str( c + 1 )
                    for c in range( args.numSurrogates ) ]

    columnNames.insert( 0, dfOut.columns[0] ) # insert time column name
    
    dfOut.columns = columnNames

    if args.outputFile :
        dfOut.to_csv( args.outputFile, index = False )

    if args.plot :
        for i in range( args.numSurrogates ):
            plt.plot( dfOut.iloc[ :, 0 ], dfOut.iloc[ :, i + 1 ],
                      label = columnNames[ i + 1 ] )
        plt.show()

#----------------------------------------------------------------------------
def RandomShuffle( df, args ):
    '''Sample the data with a uniform distribution.'''
    
    # New dataFrame with initial time column
    dataOut = DataFrame( df.iloc[ :,0 ] )

    for s in range( args.numSurrogates ) : # use pandas sample here...
        surrogate        = df[ args.column ].sample( n = df.shape[0] ).values
        dataOut[ s + 1 ] = surrogate

    return dataOut

#----------------------------------------------------------------------------
def Ebisuzaki( df, args ):
    '''The method of Ebisuzaki. 
    Journal of Climate. A Method to Estimate the Statistical Significance 
    of a Correlation When the Data Are Serially Correlated.
    https://doi.org/10.1175/1520-0442(1997)010<2147:AMTETS>2.0.CO;2 

    Presumes data are serially correlated with low pass coherence. It is:
    "resampling in the frequency domain. This procedure will not preserve 
    the distribution of values but rather the power spectrum (periodogram). 
    The advantage of preserving the power spectrum is that resampled series 
    retains the same autocorrelation as the original series. "
    '''
    
    # New dataFrame with initial time column
    dataOut = DataFrame( df.iloc[ :,0 ] )

    data          = df[ args.column ].values
    n             = df.shape[0]
    n2            = floor( n/2 )  
    mu            = mean   ( data )
    sigma         = std    ( data )
    a             = fft.fft( data )
    amplitudes    = abs( a )
    amplitudes[0] = 0

    for s in range( args.numSurrogates ) :
        thetas    = [ 2 * pi * uniform( 0, 1 ) for x in range( n2 - 1 )]
        revThetas = thetas[::-1]
        negThetas = [ -x for x in revThetas ]
        angles    = [0] + thetas + [0] + negThetas
        recf      = [ A * exp( complex( 0, theta ) )
                      for A, theta in zip( amplitudes, angles ) ]

        if n % 2 == 0 : # even length
            recf[-1] = complex( sqrt(2) * amplitudes[-1] *
                                cos( 2 * pi * uniform(0,1) ) )

        ifft = fft.ifft( recf ) / n

        realifft = [ x.real for x in ifft ]
        sdevifft = std( realifft )

        # adjust variance of surrogate time series to match original
        scaled = [ sigma * x / sdevifft for x in realifft ]
    
        dataOut[ s + 1 ] = scaled
        
    return dataOut

#----------------------------------------------------------------------------
def Seasonal( df, args ):
    '''Presume a smoothing spline represents the seasonal trend.
    Each surrogate is a summation of the trend, resampled residuals, 
    and possibly additive Gaussian noise. Default noise has a standard
    deviation that is the data range / 5.
    '''
    
    # New dataFrame with initial time column
    dataOut = DataFrame( df.iloc[ :,0 ] )

    y = df[ args.column ].values
    n = df.shape[0]

    # Presume a spline captures the seasonal cycle
    x      = arange( n )
    spline = UnivariateSpline( x, y )
    spline.set_smoothing_factor( args.smooth )
    y_spline = spline( x )

    # Residuals of the smoothing
    residual = list( y - y_spline )

    # spline plus shuffled residuals plus Gaussian noise
    noise = zeros( n )
    # If no noise specified, set std dev to data range / 5
    if args.alpha is None :
        alpha = ptp( y ) / 5
    else:
        alpha = args.alpha
        
    for s in range( args.numSurrogates ) :
        noise = [ normalvariate( 0, alpha ) for z in range( n ) ]

        dataOut[ s + 1 ] = y_spline + sample( residual, n ) + noise
    
    return dataOut

#----------------------------------------------------------------------------
def ParseCmdLine():
    
    parser = argparse.ArgumentParser( description = 'Surrogate Data' )
    
    parser.add_argument('-m', '--method',
                        dest    = 'method', type = str, 
                        action  = 'store',
                        default = 'ebisuzaki',
                        help    = 'Data generation method.')
    
    parser.add_argument('-n', '--numSurrogates',
                        dest    = 'numSurrogates', type = int, 
                        action  = 'store',
                        default = 10,
                        help    = 'Number of surrogates.')
    
    parser.add_argument('-a', '--alpha',
                        dest    = 'alpha', type = float, 
                        action  = 'store',
                        default = None,
                        help    = 'Standard deviation of seasonal noise.')
    
    parser.add_argument('-s', '--smooth',
                        dest    = 'smooth', type = float, 
                        action  = 'store',
                        default = 0.8,
                        help    = 'Smooth factor [0-1] of seasonal spline.')
    
    parser.add_argument('-c', '--column',
                        dest    = 'column', type = str, 
                        action  = 'store',
                        default = None,
                        help    = 'Input file data columns name.')
    
    parser.add_argument('-i', '--inputFile',
                        dest    = 'inputFile', type = str, 
                        action  = 'store',
                        default = None,
                        help    = 'Input file name.')
    
    parser.add_argument('-o', '--outputFile',
                        dest    = 'outputFile', type = str, 
                        action  = 'store',
                        default = None,
                        help    = 'Output file name.')

    parser.add_argument('-p', '--plot',
                        dest    = 'plot',
                        action  = 'store_true',
                        default = False,
                        help    = 'Plot results.')

    args = parser.parse_args()

    return args

#----------------------------------------------------------------------------
# Provide for cmd line invocation and clean module loading
if __name__ == "__main__":
    main()
```

**Comment by SteinPanyu** [comment]
Thank you so much!

**Comment by SteinPanyu** [comment]
FYI, I tried the surrogate function. Random_shuffle and seasonal work well. But ebisuzaki reports errors. It says that the length of values(166) does not mtach length of index (167)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-216-545c23c707bb> in <module>
      1 #generate surrogate data for both directions, replace causer with surrogate while keeping the causee the same
----> 2 df1_surrogate=pyEDM.SurrogateData(dataFrame=df_1,column='steps',method='ebisuzaki',numSurrogates=100)
      3 df1_surrogate['calories']=df['calories']
      4 df2_surrogate=pyEDM.SurrogateData(dataFrame=df_2,column='calories',method='seasonal',numSurrogates=100)
      5 df2_surrogate['steps']=df['calories']

D:\Software\Miniconda\envs\tensorflow\lib\site-packages\pyEDM\AuxFunc.py in SurrogateData(dataFrame, column, method, numSurrogates, alpha, smooth, outputFile)
    312             scaled = [ sigma * x / sdevifft for x in realifft ]
    313 
--> 314             df[ s + 1 ] = scaled
    315 
    316     elif method.lower() == "seasonal" :

D:\Software\Miniconda\envs\tensorflow\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
   3038         else:
   3039             # set column
-> 3040             self._set_item(key, value)
   3041 
   3042     def _setitem_slice(self, key: slice, value):

D:\Software\Miniconda\envs\tensorflow\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
   3114         """
   3115         self._ensure_valid_index(value)
-> 3116         value = self._sanitize_column(key, value)
   3117         NDFrame._set_item(self, key, value)
   3118 

D:\Software\Miniconda\envs\tensorflow\lib\site-packages\pandas\core\frame.py in _sanitize_column(self, key, value, broadcast)
   3762 
   3763             # turn me into an ndarray
-> 3764             value = sanitize_index(value, self.index)
   3765             if not isinstance(value, (np.ndarray, Index)):
   3766                 if isinstance(value, list) and len(value) > 0:

D:\Software\Miniconda\envs\tensorflow\lib\site-packages\pandas\core\internals\construction.py in sanitize_index(data, index)
    746     if len(data) != len(index):
    747         raise ValueError(
--> 748             "Length of values "
    749             f"({len(data)}) "
    750             "does not match length of index "

ValueError: Length of values (166) does not match length of index (167)

**Comment by SoftwareLiteracy** [comment]
Hmm... looks like a pandas data.frame error.  Perhaps there is an empty/NaN row in your input data.frame?

Here's a quick test using pyEDM data:
```
>>> from pyEDM import *

>>> sampleData['circle'].head()
   Time       x       y
0     1  0.0000  1.0000
1     2  0.0631  0.9980
2     3  0.1260  0.9920
3     4  0.1883  0.9821
4     5  0.2499  0.9683

>>> df = SurrogateData( sampleData['circle'], column = 'x', method = 'ebisuzaki', numSurrogates = 3 )
>>> df.head()
   Time       x_1       x_2       x_3
0     1 -0.091020  0.127094  0.960782
1     2 -0.033055  0.071149  0.974854
2     3  0.022278  0.017614  0.987386
3     4  0.090165 -0.042739  0.982986
4     5  0.152820 -0.103856  0.985585
```

**Comment by SteinPanyu** [comment]
I will check it out. Thanks for your information!
