### ISSUE TITLE
CCM - WARNING: ComputeError(): nan predictions found error not computed

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#23]
I'm currently encountering two issues related to `pyEDM.CCM() `using the following dataframe (The version of pyEDM was manually installed on April 7th)  : 

```
data = {'Time': list(range(2000)),
            'measurement0': list(random.sample(range(2500), 2000)),
            'measurement1': list(random.sample(range(2500), 2000))}
df = pd.DataFrame(data)

```
with : 
```

df = pyEDM.CCM( dataFrame = df, E=3, columns="measurement1", target="measurement0",
                              libSizes  = "3 1900 1", showPlot=False, sample=100);
```

The first issue is that I receive many (perhaps thousands) of the following warning message : 

` WARNING: ComputeError(): nan predictions found error not computed.`

The second issue is that after a certain amount of time, it appears that ` pyEDM.CCM()` stalls out and is no longer running. My three questions are : 

1. Can you clarify what this warning message means in regards to` pyEDM.CCM()`?
2. How many points is it computationally feasible to run using `pyEDM.CCM()`?
3. Is it possible that the warning messages and the failure of` pyEDM.CCM()` to reach completion are related? 

Thank you for your time!

**Comment by SoftwareLiteracy** [comment]
So this is version 1.8.1.0 ?
```
>>> pyEDM.__version__
'1.8.1.0'
```

1. This:
`WARNING: ComputeError(): nan predictions found error not computed.`
means that a `Simplex` prediction was output as NaN.  Here, a likely reason is the libSize is too small. 

2. How many points is it computationally feasible to run using `CCM()` ?
That is hardware and implementation dependent.  For purposes of detecting convergence, a library size increment of 1 is probably not very informative.  Nonetheless, I can see using it to get a feel for the data, but perhaps not on such a large set of libraries.  An idea is to use the `multiprocessing` module to evaulate different ranges of library sizes.  Larger libraries require more resources, so perhaps partition the libraries accordingly. 

3. Probably not.  

I notice that your dataFrame passed to `CCM()` is `df`, and you are also storing the result in `df`.  I suspect this is not what you want. 

"after a certain amount of time, it appears that pyEDM.CCM() stalls out and is no longer running."
-- How do you monitor this?

**Comment by pshankinclarke** [comment]
Thank you for your reply. Yes the version that I manually installed is 1.8.1.0 : 
```
>>> pyEDM.__version__
'1.8.1.0'
```

1.  I was able to solve the issue that generated the warning message. My starting value (i.e. 3) for the library size was too small, when I increased the starting value to 10 the error message disappeared. 
2. Can you expand on why a library size with increment of 1 is not the best for testing convergence? I assumed that the more points in the library, the more accurate the convergence test.
    If I understand your suggestion for using multiprocessing in order to make CCM tractable, then you would run sections of the library in parallel and test each section for convergence rather than the entire library. If this is your suggestion, it becomes a little bit trickier to see whether the entire library converges. For instance if you 5 sections and 2 sections that increase monotonically to a reasonable rho value, 1 section that is flat, and 2 section that decrease monotonically, then can you make any definitive conclusions about the convergence of the entire library? 
3. "after a certain amount of time, it appears that `pyEDM.CCM()` stalls out and is no longer running." Prior to find the error that generated the warning message, I monitored the number of warning messages that were being generated when I was running `pyEDM.CCM()`. Initially my output was full of warning messages, but if I let `pyEDM.CCM()` run for an entire day new warning messages would stop appearing and I assumed (maybe incorrectly) that the script/function was no longer running.

**Comment by SoftwareLiteracy** [comment]
1. Good news.  Yes, as posted earlier (in a different issue) very small library sizes don't make much sense.  I suppose there needs to be a minumum number of points in the library to allow Simplex to work (based on E and tau), but I think these minimum library size checks are not done for CCM so the user has control... hmm.  Should check that.  Thanks.
2. library size with increment of 1: Nothing wrong with it, except the large amount of processing overhead. In the example you had 2000 points and ~1900 library sizes to examine.  Each libSize is created/sampled 100 times.  So you are doing a 2000 point embedding to E = 3, plus 1900 * 100 = 190,000 library generations, and `CCM()` runs two processing threads to map x:y and y:x in parallel, so 380,000 2000 point evaluations.  Computing the "complete spectrum" of CCM values over the entire library sizes range doesn't really inform converngance better than say `libSizes = "10 1900 50", you are looking to see whether over the entire range of libSizes that CCM values increase and eventually converge. 
3. Depending on your platform, you can monitor process CPU usage with top (Linux) or Task Manager/Resource Monitor (Windows) etc. and see if the parent Python process is running at full CPU.

**Comment by pshankinclarke** [comment]
Great Idea thanks !

**Comment by pshankinclarke** [comment]
I'd like to follow up on some of the math you outlined in 2.) in order to improve my understanding of CCM :

1. What is a "point evaluation" and why is connected to the original (i.e. 2000) number of points in the library? 
2. What is the most computationally expensive part of CCM? The embedding, the sampling, the threading, the point evaluation or something else? I'm guessing this might be dependent on the size of the library. So to narrow my question, consider library sizes over 10,000 points.  
3. You said for a library of 2000 points that it would be sufficient to use libSizes = "10 1900 50" to test for convergence. Would it also be sufficient to use smaller library sizes, say  libSizes = "10 500 50" in order to test for convergence given the same number of points (i.e. 2000) in the original library? It appears that given the same libSizes, the greater the size of the  library the more time it takes for CCM to run. I'm assuming this is because of the number of "point evaluations" that need to occur is higher if the original library size is larger. 
4. Do you think it's best to run CCM several times and average the results?

**Comment by SoftwareLiteracy** [comment]
1. By "2000 point evaluations" I meant embedding 2000 points to E, and then doing the Simplex prediction on these 2000 points. Sorry for the lack of clarity. 
2. What is the most computationally expensive part of CCM? The convergence evaluations at each libSize. Yes, smaller libraries consume less resources.  
3. That depends on where in the libSizes "convergence" happens.  I like to see a value near the full library size. Looking for conergence can be done "sparsely", with fairly large intervals between libSIzes.
4. I don't see much need to average CCM results from different runs, as long as `sample` is large enough. 

 btw: I tried your example on my machine and it ran for more than 8 hours with 2 CPU at 100% (as expected) before I killed it.  

Here's examples with sparse libSizes, that, as expected, shows no evidence of convergence:
```
>>> from pyEDM import *
>>> from pandas import DataFrame

>>> data = {'Time': list(range(2000)),'x': list(random.sample(range(2500), 2000)),'y':list(random.sample(range(2500), 2000))}
>>> df = DataFrame( data )

>>> startTime = time.time(); cm = CCM( dataFrame = df, E = 3, columns = 'x', target = 'y', libSizes  = "100 1990 500", showPlot = False, sample = 100 ); time.time() - startTime
69.86491990089417
>>> cm
   LibSize       x:y       y:x
0    100.0 -0.015283 -0.015668
1    600.0 -0.034053 -0.008602
2   1100.0 -0.053677 -0.018909
3   1600.0 -0.066955 -0.029199

>>> startTime = time.time(); cm = CCM( dataFrame = df, E = 3, columns = 'x', target = 'y', libSizes  = "100 1990 200", showPlot = False, sample = 100 ); time.time() - startTime
204.9758062362671
>>> cm
   LibSize       x:y       y:x
0    100.0 -0.016058 -0.010618
1    300.0 -0.020229 -0.004000
2    500.0 -0.030825 -0.010279
3    700.0 -0.036757 -0.014394
4    900.0 -0.041943 -0.017464
5   1100.0 -0.052177 -0.019224
6   1300.0 -0.055758 -0.021565
7   1500.0 -0.063640 -0.027985
8   1700.0 -0.071506 -0.033372
9   1900.0 -0.079303 -0.040963
```

**Comment by SoftwareLiteracy** [comment]
Just for fun... I wrote a pyEDM app that uses the python `multiprocessing` module to run `CCM` with process parallelism.  The idea is that you break up the `libSizes` across multiple cores/processes.  Here's an example using data:
```
from pandas import read_csv
df = read_csv( 'TTFF_data.csv' )
df.head()
         Date    Qout      Qin  WCA3A  NESRS     Za   PET  Rain
0  1965-01-01  1465.1  1465.06  10.34   6.64  10.50  0.83  0.14
1  1965-01-08  1386.8  1465.06  10.33   6.95  10.46  0.80  0.00
2  1965-01-15  1099.1  1386.81  10.29   7.37  10.41  0.80  0.02
3  1965-01-22   908.1  1099.06  10.22   7.41  10.37  0.88  0.06
4  1965-01-29   725.3   908.09  10.12   7.37  10.33  0.88  0.31
```
Using 5 cores and a libSizes list of 4 items.  The first item uses the start, start, increment format, the last three just list of libSizes:
```
> ./CCM-Multiprocess.py -i TTFF_data.csv -E 3 -c NESRS -t Qout -l "100 500 100" "750 1000" "1500" "2000" -s 100 -C 6
Result has  4  items.
   LibSize  NESRS:Qout  Qout:NESRS
0    100.0    0.785558    0.872167
1    200.0    0.797950    0.879555
2    300.0    0.801767    0.881842
3    400.0    0.804877    0.883329
4    500.0    0.805993    0.886233
0    750.0    0.807168    0.888511
1   1000.0    0.808126    0.890096
0   1500.0    0.806959    0.893097
0   2000.0    0.805841    0.895669
Normal Exit elapsed time: 53.11
```
Now, put all the libSizes into one list so there is no parralelism:
```
> ./CCM-Multiprocess.py -i ../cppEDM/data/TTFF_data.csv -E 3 -c NESRS -t Qout -l "100 200 300 400 500 750 1000 1500 2000" -s 100 -C 6
Result has  1  items.
   LibSize  NESRS:Qout  Qout:NESRS
0    100.0    0.788710    0.874646
1    200.0    0.797553    0.879510
2    300.0    0.802204    0.881552
3    400.0    0.804874    0.884513
4    500.0    0.805881    0.885485
5    750.0    0.807420    0.889104
6   1000.0    0.808237    0.890235
7   1500.0    0.806933    0.893222
8   2000.0    0.805909    0.895757
Normal Exit elapsed time: 153.85
```
Three times as long.  The idea is to submit large libSizes to separate cores. 

Application code:

```
#! /usr/bin/env python3

import time, argparse
from   multiprocessing import Pool
from   itertools       import repeat

from pandas import read_csv, concat

from pyEDM  import CCM

#----------------------------------------------------------------------------
# Main module
#----------------------------------------------------------------------------
def main():
    '''Use multiprocessing Pool to process parallelise CCM.
       The libSizesList (-l) argument specifies a list of CCM libSizes.
       libSizesList arguments can be any valid CCM libSizes representations.

       For exmaple: ./CCM-Multiprocess.py -l "100 500 100" "750 1000" "1500"
    '''
    
    startTime = time.time()
    
    args = ParseCmdLine()
    
    Process( args )

    elapsedTime = time.time() - startTime
    print( "Normal Exit elapsed time:", round( elapsedTime, 2 ) )

#----------------------------------------------------------------------------
def Process( args ):

    data = read_csv( args.inputFile )

    # Create iterable for Pool.starmap, use repeated copies of args, data
    poolArgs = zip( args.libSizesList, repeat( args ), repeat( data ) )

    # Use pool.starmap to distribute among cores
    pool = Pool( processes = args.cores )
    
    # starmap: elements of the iterable argument are iterables
    #          that are unpacked as arguments
    CMList = pool.starmap( CrossMapFunc, poolArgs )

    print( "Result has ", str( len( CMList ) ), " items." )

    df = concat( CMList )
    print( df )

    if args.outputFile :
        df.to_csv( args.outputFile )

#----------------------------------------------------------------------------
def CrossMapFunc( libSizes, args, data ):
    '''Call pyEDM CCM using the libSizes, args, and data'''
    
    cm = CCM( dataFrame       = data,
              E               = args.E,
              exclusionRadius = args.exclusionRadius,
              columns         = args.column,
              target          = args.target,
              libSizes        = libSizes,  # Not from args
              sample          = args.sample,
              showPlot        = False )

    return cm
    
#----------------------------------------------------------------------------
def ParseCmdLine():
    
    parser = argparse.ArgumentParser( description = 'Test Program' )
    
    parser.add_argument('-i', '--inputFile',
                        dest    = 'inputFile', type = str, 
                        action  = 'store',
                        default = None,
                        help    = 'Input data file.')
    
    parser.add_argument('-o', '--outputFile',
                        dest    = 'outputFile', type = str, 
                        action  = 'store',
                        default = None,
                        help    = 'Output file.')

    parser.add_argument('-E', '--E',
                        dest    = 'E', type = int, 
                        action  = 'store',
                        default = 3,
                        help    = 'Embedding dimension E.')

    parser.add_argument('-x', '--exclusionRadius',
                        dest    = 'exclusionRadius', type = int, 
                        action  = 'store',
                        default = 0,
                        help    = 'Exclusion Radius.')

    parser.add_argument('-c', '--column',
                        dest    = 'column', type = str, 
                        action  = 'store',
                        default = None,
                        help    = 'Input file data column name.')
    
    parser.add_argument('-t', '--target',
                        dest    = 'target', type = str, 
                        action  = 'store',
                        default = None,
                        help    = 'Input file data target name.')
    
    parser.add_argument('-l', '--libSizesList', nargs = '+',
                        dest    = 'libSizesList', type = str, 
                        action  = 'store',
                        default = [ "100 300", "500 700",
                                    "1000 1500", "1800 2000" ],
                        help    = 'CCM library sizes.')

    parser.add_argument('-s', '--sample',
                        dest    = 'sample', type = int, 
                        action  = 'store',
                        default = 100,
                        help    = 'CCM samples.')

    parser.add_argument('-C', '--cores',
                        dest    = 'cores', type = int, 
                        action  = 'store',
                        default = 4,
                        help    = 'Multiprocessing cores.')

    parser.add_argument('-p', '--plot',
                        dest    = 'plot',
                        action  = 'store_true',
                        default = False,
                        help    = 'Plot results.')

    args = parser.parse_args()

    return args

#----------------------------------------------------------------------------
# Provide for cmd line invocation and clean module loading
if __name__ == "__main__":
    main()
```

**Comment by pshankinclarke** [comment]
Wow! This is excellent! It really clears up the question marks I had surrounding  parallelizing CCM . I also see the same trend with my dataset : 
```

$ python3 CCM-Multiprocess.py -i multiprocessing_data.csv -E 3 -c x -t y -l "100 500 100" "750 1000" "1500" "1900" -s 100 -C 6
Result has  4  items.
   LibSize       x:y       y:x
0    100.0 -0.001449  0.001834
1    200.0 -0.003372 -0.001319
2    300.0 -0.004271  0.000590
3    400.0 -0.003341 -0.001062
4    500.0 -0.001089 -0.000985
0    750.0 -0.001172 -0.000294
1   1000.0 -0.003794 -0.000830
0   1500.0 -0.005636 -0.000826
0   1900.0 -0.002532 -0.001725
Normal Exit elapsed time: 212.96
$ python3 CCM-Multiprocess.py -i multiprocessing_data.csv -E 3 -c x -t y -l "100 500 100 750 1000 1500 1900" -s 100 -C 6
Result has  1  items.
   LibSize       x:y       y:x
0    100.0 -0.001460  0.000686
1    500.0 -0.002600  0.000616
2    100.0 -0.000439  0.002625
3    750.0 -0.002614 -0.000950
4   1000.0 -0.002884 -0.001104
5   1500.0 -0.002494 -0.001719
6   1900.0 -0.002999 -0.001124
Normal Exit elapsed time: 605.78
```

**Comment by pshankinclarke** [comment]
Following-up on this issue, as was previously demonstrated parallelizing convergence tests with ~ 2,000 points of data works very well! However trying to use python multiprocessing with different libSize ranges for a data set of 15,000 points appears significantly more difficult. Even for small library sizes (e.g. 1000 points) issues arise. To summarize my experience, a 15,000 point data set ran across multiple cores requires significant memory usage by each core (I'm monitoring the processes with "glances"). My hypothesis is that at some point the sum of processes crosses some limit in the amount of system resources that are available to use, and the convergence tests are killed by the system.

In response I've had to revert to using standard non-parallelized convergence tests for library sizes up to 1100 points (for a dateset of 15,000 points). The non-parallelized convergence tests seem to work better because only one core is consuming memory at any given time.

 I had a few questions regarding this problem :

1 . ) If a data set contains 15,000 points, is it necessary to test library sizes close to 15,000, or is it sufficient to test lower library sizes (e.g. 1000 points) since each library size is being sampled 100 times ?  
2.) If it is better to use library sizes close to 15,000, other than using better hardware, are there any known methods for making these large convergence tests possible ? 

Thank you so much for your time !

**Comment by SoftwareLiteracy** [comment]
I would imagine that yes, you can overwhelm your system with memory usage requests.  That should be easy to monitor.  When memory usage is high, the system will likely start page swapping memory to disk.  Very slow.  Plus, if all CPU is fully utilised, there is no free overhead for coordination of multiple processes.  Also slow. 

Are you sure that the processes are being killed by the system?  I have not seen this.  I do see that they can run for very long times.

Generally, allocation and monitoring of system resources is primal in high performance computing. 

1. If a data set contains 15,000 points, is it necessary to test library sizes close to 15,000?  Depends on the system.  I suspect in many cases it is not.  The presumption of increasing library size is that one is getting more complete representations of the dynamics with a larger state space.  The complexity and range of the dynamics (states) will determine how many points are needed for that.  As always, it is problem/system dependent.  I would think that once "convergence" is seen, the curve flattens, then additional library states are not changing the picture (providing more information).  

2. If it is better to use library sizes close to 15,000, other than using better hardware, are there any known methods for making these large convergence tests possible ?  As above, maximal library size is problem dependent.  Does it take 15K points to reasonably represent the state-space?  Perhaps not.  Reducing the `sample` size can help.  It is a linear scale factor on run time since it is the number of times each `libSize` is resampled from the state space.  For large scale problems, perhaps using a lower `sample` is a starting point.  We have already mentioned using a sparse `libSizes` domain.  The other suggestion is to get more processing power (memory and cores) it is obtainable today in the cloud.

**Comment by pshankinclarke** [comment]
Thank you!
