### ISSUE TITLE
Multiple subject CCM

### ISSUE THREAD

**Issue by SteinPanyu** [SugiharaLab/pyEDM#24]
Hello, 

I am working on multiple subject CCM and found this blog.
https://sites.google.com/site/dkyogoku/redm-no-shii-fang
(You may translate it via google translate)

![image](https://user-images.githubusercontent.com/80038088/120592961-aef04180-c479-11eb-9ce4-4b5e287f80f6.png)

However, it is for rEDM, in pyEDM, how can we deal with this issue? 
Shall we use "1, 30; 31, 60; 61, 90" for libSize of CCM fucntion?

ps: It seems that CCM function recognizes it as 6 points of libSize... 1 30 31 60 61 and 90

Any help would be appreciated:-)

**Comment by nonlinearnature** [comment]
Yes! This is definitely possible and very useful. The basic idea is set out in Clark et al.:

https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/14-1479.1

Within rEDM and pyEDM I believe the 1.8 syntax now makes this straightforward, but you need to specify the breaks between replicate systems in "lib" and "pred", not in libSize. It's possible this is still only well behaved in Simplex() and SMap(). If you'd like to test that, I can provide an R function that will compute cross-map skill for a single library (so not the full convergence calculation at multiple library sizes) using Simplex(...,embedded=TRUE) that you can double check against ccm() output.

**Comment by SoftwareLiteracy** [comment]
Thank you for these posts.  Yes, in version 1.8 and beyond you can specify "breaks" in `lib`.  It does however not yet support breaks in `pred`.  Outputs are based on the segemented `lib`, but will be given at all time indices specified in the contiguous `pred`.  

For example
```
s = Simplex( dataFrame = sampleData["block_3sp"], lib = "1 80 111 140", pred = "181 190",
             E = 3, columns = "x_t", target = "x_t" )
```
or if you prefer you can pass in `lib = [1, 80, 111, 140]`

**Comment by SteinPanyu** [comment]
Thanks. I will check it out!
