### ISSUE TITLE
I'm stuck at this step "Build cppEDM library: cd pyEDM\cppEDM\src; make"

### ISSUE THREAD

**Issue by lupupu** [SugiharaLab/pyEDM#25]
Too many requirements make installation difficult.

**Comment by cameronosmith** [comment]
Does your application require you to build from source, or is your platform not supported by our prebuilt wheels (installing via pip)?

**Comment by SoftwareLiteracy** [comment]
As noted, the [Documentation](https://sugiharalab.github.io/EDM_Documentation/) has an `Installation` section.
