### ISSUE TITLE
How to find the right number of embedding dim

### ISSUE THREAD

**Issue by lila167** [SugiharaLab/pyEDM#26]
Hi,

I have a dataframe (60x3) with columns being my variables. Running ```pyEDM.CCM(dataFrame = sol_df, E = 3, columns="0", target="1",libSizes  = "10 30 10",showPlot=True, sample=10)``` jupyter kernel dies immediately without any specific error. Could you please help me to find the problem?

Many thanks

**Comment by lila167** [comment]
I found the problem, columns could not be numbers. Renaming them solved the problem. However, I still wonder what is the right number of embedding dimensions to use. Can one estimate that?

**Comment by SoftwareLiteracy** [comment]
The first problem you describe seems to be a bug.  In the legacy code column and target names could be column numbers (index of the column), where the columns themselves were not labeled,  The new version tries to make this explicit by using named columns, however, code was included to try and accomodate the old, non-named functionality in cases where `columns` and `target` are integers.   This should probably be deprecated.  

Regarding the selection of embedding dimension `E`, please refer to the [online documents](https://sugiharalab.github.io/EDM_Documentation/).  The function [EmbedDimension](https://sugiharalab.github.io/EDM_Documentation/edm_functions/#embeddimension), and [examples](https://sugiharalab.github.io/EDM_Documentation/algorithms_high_level/).

**Comment by SoftwareLiteracy** [comment]
The original issue of data columns as numbers has been fixed in version 1.9.1.

The legacy form of columns specified by column index has been deprecated.  All dataFile or dataFrame objects must have a header with column names.  This is consistent with the documentation.  Column names can be numbers, but will operate as unique labels in column selection, not as numeric values/indices.

**Comment by shuping-li** [comment]
I am trying to find out the causal relationship between two variables, and I am experiencing the same issue with lila167.
I went through the examples you provided and still feel confused about the embedding dimension:
1. Should I determine the parameter E in function `py.EDM.CCM()` referring to the results of `pyEDM.EmbedDimension()`?
2. For function `pyEDM.EmbedDimension()`, what should be based on when choosing lib and pred?
Thanks a lot!

**Comment by SoftwareLiteracy** [comment]
Hi shuping-li, yes, one normally uses `EmbedDimension` to identify a reasonable `E` for a given timeseries.  That value of `E` is then used in `CCM` for the target timeseries. 

The choice of `lib` and `pred` in `EmbedDimension` is dependent on several factors.  In the case of a `CCM` analysis it makes sense to set `lib` = `pred` = N - `tau` * `E`, which corresponds to the maximum library that `CCM` can use.

**Comment by shuping-li** [comment]
Would you elaborate a little bit on what factors to consider when choosing reasonable `lib `and `pred`? Because I found the results varying a lot with different lengths of `lib `and `pred`.
Another thing is, in the example page the function `pyEDM.EmbedDimension()` is used to calculate E for the single timeseries (i.e., `TentMap`), but in the case of `CCM `there are two timeseries `anchovy `and `np_sst`, I am curious how do I decide on the timeseries to calculate E?

**Comment by SoftwareLiteracy** [comment]
Hopefully, `E` from `EmbedDimension` is not very different for the `columns` and `target` timeseries used in `CCM`. If they are widely different, this can be an indication (to me) that the method is not suitable. `CCM` relies on the presumption that the state-spaces reconstructed from the two tiimeseries are affine representations of the same underlying dynamics.  If `E` is widely different, say 3 and 7, then this presumption is questionable (to me). 

I would expect that in cases where there are small differences, the `target` `E` is the one to use.  I will verify this opinion with the experts and feedback if my expectation is different from the consensus.

As noted, the question of `lib` and `pred` is a bit complex.  `lib` defines the state-space.  Observations from `lib` rows of the time series are used to create the state-space from which the predictions are made.  Normally, one wants to ensure the state-space entirely maps the system dynamical behavior.  More is better. 

`pred` are the timeseries observation rows (the point in the E-dimensional state-space) from which the EDM state-space projections are made.  Whether one uses _in-sample_ (`pred`∈`lib`) or _out-of-sample_ models (`pred`∉ `lib`) is a decision of the modeler. 

Here is my view from a recent paper:

> When models are used in an operational forecast system it is typical to assess model fitness on _out-of-sample_ data, that is, the model is trained on a subset of available data with fitness assessed on a prediction (validation) set disjoint from the training data.  Out-of-sample prediction characterizes model stability and the ability to generalize to untrained data.
> 
> _In-sample_ models, where the training and prediction sets overlap, are informative when discovering/assessing the ability of the model to represent system dynamics. For example, as a function of state-space variables and their interactions, or, in response to noise/confounded states.

To me, _in-sample_ can be used to characterize the state-space or interactions, _out-of-sample_ to assess model validity and performance.
