### ISSUE TITLE
Minor doc error

### ISSUE THREAD

**Issue by pmahon3** [SugiharaLab/pyEDM#27]
In the documentation the default value for showPlot in PredictNonlinear is False:
https://github.com/SugiharaLab/pyEDM/blob/0a5ed0c852325b4813a3a622f06a46961e332edc/doc/pyEDM.pdf

...but value is set to True here: 
https://github.com/SugiharaLab/pyEDM/blob/0a5ed0c852325b4813a3a622f06a46961e332edc/pyEDM/CoreEDM.py#L446

**Comment by SoftwareLiteracy** [comment]
Thanks for the correction.  In fact, all three convenience functions (`EmbedDimension PredictInterval PredictNonlinear`) have this doc error.  Document updated.
