### ISSUE TITLE
import pyEDM works but import EDM doesn't 

### ISSUE THREAD

**Issue by 4rachelgreen** [SugiharaLab/pyEDM#3]
Which one is it? I am unable to bring up EDM.Examples() or any of the functions after a fresh install

**Comment by SoftwareLiteracy** [comment]
Hi Rachel, 

pyEDM is currently in development, but it should work.

The current version should be import pyEDM, then pyEDM.Examples().

**Comment by 4rachelgreen** [comment]
I am running on linux and followed the instructions from the Documentation to build from source. 
When I run 
```python
pyEDM.Examples
```
I am getting the following:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-20488deb7360> in <module>()
----> 1 pyEDM.Examples()

AttributeError: module 'pyEDM' has no attribute 'Examples'
```

**Comment by cameronosmith** [comment]
Hi Rachel, does this issue still exist?

**Comment by 4rachelgreen** [comment]
Hi Cameron the issue seems to have been resolved thanks!

**Comment by cameronosmith** [comment]
Good to hear, Rachel. Sorry for the trouble while we iron out the kinks of the interface. Best.
