### ISSUE TITLE
Clarification:Smap prediction of one species using another species

### ISSUE THREAD

**Issue by UhP88** [SugiharaLab/pyEDM#33]
I have been using pyEDM version 1.10.2.0 to predict one species (sp1) using another species (sp2). Is it possible to use Smap function on the dataframe (df) containing scaled species abundance data as below? and then use the Result['predictions'] to plot Observations and Predictions values.? 
Could we use the pyEDM.ComputeError function to check the correlation between Observations and Predictions values.? 
I also want to know the inference of Pred_Variance and how it could be used to calculate forecast uncertainty?

Result = pyEDM.SMap( dataFrame=df, lib = "1 200", pred = "1 200",  theta = theta_sp2, E = E_sp2, Tp = 1,verbose = True, showPlot = False, columns = sp2, target=sp1)

Sorry for may questions, 
Thank you so much in advance.

**Comment by SoftwareLiteracy** [comment]
I think the answer is yes to all questions except one. 

I may be wrong, but I do not understand `Pred_Variance` to be a metric of forecast uncertainty.  It is more a measure of the state-space simplex or localized SMap extent for a specific prediction.  

For the other questions, here is an example. To see a plot of observations vs predictions, with annotation of model error, use `showPlot = True`:

```Python
>>> from pyEDM import *
>>> pyEDM.__version__
'1.12.2.0'
>>> sampleData.keys()
dict_keys(['TentMap', 'TentMapNoise', 'circle', 'block_3sp', 'sardine_anchovy_sst', 'Lorenz5D', 'SumFlow_1980-2005'])
>>> df.shape
(198, 10)
>>> df.head(3)
   time       x_t     x_t-1     x_t-2  ...     y_t-2       z_t     z_t-1     z_t-2
0     3 -1.917685  1.244882 -0.741863  ... -1.268104  1.535239 -0.481583 -1.863980
1     4 -0.962318 -1.917685  1.244882  ...  1.488887 -1.492956  1.535239 -0.481583
2     5  1.331875 -0.962318 -1.917685  ... -0.113188 -1.119476 -1.492956  1.535239
>>> xy = SMap( dataFrame = df, E = 3, theta = 3.3, lib = [1, 198], pred = [1, 198], columns = 'x_t', target = 'y_t' )
>>> xy.keys()
dict_keys(['predictions', 'coefficients'])
>>> 
>>> xy['predictions'].head(3)
  time  Observations  Predictions  Pred_Variance
0    5      2.385041          NaN            NaN
1    6     -0.675346     0.273885       1.010544
2    7     -0.010639    -0.857393       0.591914
>> xy['coefficients'].head(3)
  time        C0  ∂y_t/∂x_t(t-0)  ∂y_t/∂x_t(t-1)  ∂y_t/∂x_t(t-2)
0    5       NaN             NaN             NaN             NaN
1    6 -0.653494        0.874553       -0.264623        0.256595
2    7 -0.116735        0.426516       -0.077462        0.300305
>>> err = ComputeError( xy['predictions']['Observations'], xy['predictions']['Predictions'])
>>> err
{'MAE': 0.637365208112624, 'RMSE': 0.7841565752293902, 'rho': 0.5647479404548299}
```

**Comment by SoftwareLiteracy** [comment]
For data discovery, the [jpyEDM](https://github.com/SugiharaLab/jpyEDM#empirical-dynamic-modeling-edm-jupyter-notebook) jupyter notebook gui for pyEDM can save a lot time.

**Comment by UhP88** [comment]
Thank you so so much for the clarification. I have few more points to clarify... 
In the case of a multivariate data set, could we use a similar species x time data set? Or should it be first embedded as in block_3sp? In that case which E and theta value should be used ? 
I also would like to know if there is a way of quantifying how accurately we could predict a sp.1 using several other species.

**Comment by SoftwareLiteracy** [comment]
Please see the [documentation](https://sugiharalab.github.io/EDM_Documentation/embedding_parameters/) where this is discussed. 

Multivariate data is often used, specfied with `embedded = True`. This tells the code to **not embedd** the input data `columns`, but to use them as-is (considered already embedded) where each column defines a 1-D dimensional vector out of the `E` columns. The `E` parameter is ignored since the code will set `E` to the number of `columns`. 

`SMap` is a little different from `Simplex` since it computes/returns a fit coefficient for each target/column_i pair. If the code finds there is more than one `columns`, it requires `embedded = True` for `SMap` to ensure correct alignment of the output coefficient labels. 

`Simplex` doesn't have this restriction since it only computes a 1-D prediction, not coefficients.  In `Simplex` using multiple `columns` with `E > 1` and the default `embedded = False` will create a *mixed embedding* -- a multivariate embedding where each column is time-delay embeded to `E`.  The total state-space dimension will then be N_columns * E.  If one sets `embedded = True`, it is the same as `SMap`, each column is considered a 1-D state-space vector and `E` is internally set to the number of columns. 

If you wish to have a mixed-embedding (multiple time-delay embedded state-space vectors) with `SMap`, then yes, you would first create the embedding with `Embed()` or otherwise, then pass that to `SMap` with `embedded = True`.

The last question: if there is a way of quantifying how accurately we could predict a sp.1 using several other species. -- I suspect those with more experience applying the code have a better answer than I can provide. My notion is that `Multiview()` might be a way to approach this.  Simply, using multivariate embeddings and removing selected `columns` might be a way.  First assessing links between variables using `CCM` is often done.

My understanding of the algorithms as applications is roughly:
|  API | Application |
| ----- |:-------:|
| `Simplex` | Prediction and basis of CCM, Multiview |
| `Smap` | Time-varying interactions and nonlinear localisation |
| `CCM` | Causal links over the entire state-space |
| `Multiview` | Multivariable combinations for optimal predictability (state-space information) |

**Comment by SoftwareLiteracy** [comment]
```Python
>>> from pyEDM import *
>>> pyEDM.__version__
'1.12.2.0'
>>> sampleData.keys()
dict_keys(['TentMap', 'TentMapNoise', 'circle', 'block_3sp', 'sardine_anchovy_sst', 'Lorenz5D', 'SumFlow_1980-2005'])
>>> df = sampleData['block_3sp']
>>> df.shape
(198, 10)
>>> df.columns.to_list()
['time', 'x_t', 'x_t-1', 'x_t-2', 'y_t', 'y_t-1', 'y_t-2', 'z_t', 'z_t-1', 'z_t-2']

# Multivariate SMap predicting x_t from 2-D [ y_t, z_t ]
>>> x_yz = SMap( dataFrame = df, lib = [1,198], pred = [1,198], target = 'x_t', columns = 'y_t z_t', theta = 3.14, embedded = True )
>>> x_yz['coefficients'].head(3)
  time        C0  ∂x_t/∂y_t  ∂x_t/∂z_t
0    3       NaN        NaN        NaN
1    4 -0.034552  -0.204527   0.503233
2    5 -0.517843   0.023091  -0.694894

# Since df already has a mixed embedding
>>> x_x1x2yz = SMap( dataFrame = df, lib = [1,198], pred = [1,198], target = 'x_t', columns = 'x_t-1 x_t-2 y_t z_t', theta = 3.14, embedded = True )
>>> x_x1x2yz['coefficients'].head(3)
  time        C0  ∂x_t/∂x_t-1  ∂x_t/∂x_t-2  ∂x_t/∂y_t  ∂x_t/∂z_t
0    3       NaN          NaN          NaN        NaN        NaN
1    4  0.533335    -0.049093    -0.059410  -0.219652  -0.012125
2    5 -1.191129    -0.952665     0.230351  -0.013715  -0.075402

# Create a mixed embedding using Embed
>>> embed_xzE4 = Embed( dataFrame = df, E = 4, columns = 'x_t z_t' )
>>> embed_xzE4.head(5)
   x_t(t-0)  x_t(t-1)  x_t(t-2)  x_t(t-3)  z_t(t-0)  z_t(t-1)  z_t(t-2)  z_t(t-3)
0 -1.917685       NaN       NaN       NaN  1.535239       NaN       NaN       NaN
1 -0.962318 -1.917685       NaN       NaN -1.492956  1.535239       NaN       NaN
2  1.331875 -0.962318 -1.917685       NaN -1.119476 -1.492956  1.535239       NaN
3 -0.817083  1.331875 -0.962318 -1.917685  0.746658 -1.119476 -1.492956  1.535239
4  0.743586 -0.817083  1.331875 -0.962318  0.063089  0.746658 -1.119476 -1.492956

# Insert the required first column of time
>>> embed_xzE4.insert( 0, 'time', df['time'] )
>>> embed_xzE4.head(5)
   time  x_t(t-0)  x_t(t-1)  x_t(t-2)  x_t(t-3)  z_t(t-0)  z_t(t-1)  z_t(t-2)  z_t(t-3)
0     3 -1.917685       NaN       NaN       NaN  1.535239       NaN       NaN       NaN
1     4 -0.962318 -1.917685       NaN       NaN -1.492956  1.535239       NaN       NaN
2     5  1.331875 -0.962318 -1.917685       NaN -1.119476 -1.492956  1.535239       NaN
3     6 -0.817083  1.331875 -0.962318 -1.917685  0.746658 -1.119476 -1.492956  1.535239
4     7  0.743586 -0.817083  1.331875 -0.962318  0.063089  0.746658 -1.119476 -1.492956

# Have to reduce lib & pred to 196 since 2 rows with NaN [from z_t(t-2),...] will be removed in SMap
>>> x_x1x2_z0z1 = SMap( dataFrame = embed_xzE4, lib = [1,196], pred = [1,196], target = 'x_t(t-0)', columns = 'x_t(t-1)  x_t(t-2) z_t(t-1)  z_t(t-2)', theta = 3.14, embedded = True )
WARNING: SMap() nan rows detected in columns or target. 2 deleted. Original number of rows 198.
>>> x_x1x2_z0z1['coefficients'].head(5)
  time        C0  ∂x_t(t-0)/∂x_t(t-1)  ∂x_t(t-0)/∂x_t(t-2)  ∂x_t(t-0)/∂z_t(t-1)  ∂x_t(t-0)/∂z_t(t-2)
0    7       NaN                  NaN                  NaN                  NaN                  NaN
1    8 -0.831727            -0.584461             0.129330            -0.110575            -0.112636
2    9  0.375508             0.277808            -0.189219             0.068092            -0.054478
3   10 -0.826663            -1.188786            -0.167253            -0.309445             0.178168
4   11 -0.268646             1.206991             0.496060            -0.189926             0.274852
```

**Comment by UhP88** [comment]
I am so thankful for the detailed explanation with examples. I think I got my queries clarified.

**Comment by UhP88** [comment]
I tried out the Smap function after embedding data from the sample data set sardine_anchovy_sst, however gives a run time error. A similar error occured when I tried to use my own data as well. What could be the reason.. 

target =  'anchovy'
causes = ['np_sst']
embed_anch = pyEDM.Embed(dataFrame=sardine_anchovy_sst, E=3, columns=target)
for cause in causes:
    embed_anch[cause] = sardine_anchovy_sst[cause].values
embed_anch.insert(loc=0, column='Time', value=range(len(embed_anch)))
embed_anch

results = pyEDM.SMap( dataFrame=embed_anch,lib = "1 75", pred = "1 75", \
     theta = 3.14, E = 3, Tp = 1, embedded=True, \
     verbose = True, showPlot = True, columns = ' '.join(embed_anch.columns[1:]), target=target+'(t-0)’)

Gives a    RuntimeError: Lapack_SVD(): dgelss failed.

**Comment by SoftwareLiteracy** [comment]
That error usually means the SMap SVD is ill-posed.  

Your code works here, version 1.12.2:
```Python
>>> from pyEDM import *
>>> sardine_anchovy_sst = sampleData['sardine_anchovy_sst']
>>> target = 'anchovy'
>>> causes = ['np_sst']
>>> embed_anch = pyEDM.Embed(dataFrame=sardine_anchovy_sst, E=3, columns=target)
>>> for cause in causes:
...     embed_anch[cause] = sardine_anchovy_sst[cause].values
... 
>>> embed_anch.insert(loc=0, column='Time', value=range(len(embed_anch)))
>>> embed_anch.head(3)
   Time  anchovy(t-0)  anchovy(t-1)  anchovy(t-2)    np_sst
0     0     -0.007599           NaN           NaN -0.347846
1     1     -0.009602     -0.007599           NaN  0.328734
2     2     -0.008444     -0.009602     -0.007599  1.610270
>>> results = pyEDM.SMap( dataFrame=embed_anch,lib = "1 75", pred = "1 75", theta = 3.14, E = 3, Tp = 1, embedded=True,showPlot = True, columns = ' '.join(embed_anch.columns[1:]), target=target+'(t-0)' )
WARNING: SMap() nan rows detected in columns or target. 2 deleted. Original number of rows 78.
>>> results['coefficients'].head(5)
  Time        C0  ...  ∂anchovy(t-0)/∂anchovy(t-2)  ∂anchovy(t-0)/∂np_sst
0    4       NaN  ...                          NaN                    NaN
1    5  0.189354  ...                     1.530629              -0.164803
2    6  0.035450  ...                    -0.024521              -0.152608
3    7  0.051683  ...                     0.075199              -0.093033
4    8  0.044564  ...                     0.900776              -0.035196

[5 rows x 6 columns]
>>> results['predictions'].head(5)
  Time  Observations  Predictions  Pred_Variance
0    4     -0.007750          NaN            NaN
1    5     -0.009531     0.173430       0.237802
2    6     -0.009964     0.138306       0.250566
3    7     -0.007800     0.104146       0.235167
4    8     -0.007458     0.019498       0.107545
```

**Comment by UhP88** [comment]
Sorry for re-opening this thread. I have a question again on using Smap-prediction. I used https://khigashi1987.github.io/pyEDM_Maizuru/  code to predict for example sp.A using sp.B+sp.C. When choosing sp.B and sp.C, I looked at significant causality with twin surrogates. The embedding and Smap prediction was done as below
<img width="875" alt="Screen Shot 2022-11-10 at 12 16 54" src="https://user-images.githubusercontent.com/78030818/200992469-1ac78304-4eb2-4b8d-b11f-3b7a45352fb4.png">

My question is how could we use rho, RMSE and MAE values to evaluate our prediction? Sometimes when the prediction line shows the same variation as observation but seems to be shifted 1 or 2 time points ahead the rho value is quite low and I find it difficult to validate my prediction graph using the rho (correlation between Obs and Pred)

**Comment by UhP88** [comment]
Thank you so much for the reply.. to evaluate across different values of Tp, could I use  a similar code mentioned in #35 issue ?

**Comment by SoftwareLiteracy** [comment]
Yes.  Although it's a bit different since `CCM` returns two results, forward and inverse mapping.  Also, the serial loop doesn't take advantage of multicore. 

Here's an app that uses `multiprocessing` to evaluate SMap over a range of Tp : [SMap-Multiprocess-Tp.py](https://github.com/SugiharaLab/pyEDM/blob/master/pyEDM/etc/apps/SMap-Multiprocess-Tp.py). 

Results are returned in a dictionary of SMap dictionaries, one for each Tp.

**Comment by UhP88** [comment]
Oh thank you so much for providing this app. I'm sorry for asking a primitive question, but how could we execute this code using our data?

**Comment by SoftwareLiteracy** [comment]
This script is a command line application. The `argparse` module is used to create the command line interface and options.  On Linux, at the command prompt:
```
apps> ./SMap-Multiprocess-Tp.py -P
dict_keys(['Tp-5', 'Tp-4', 'Tp-3', 'Tp-2', 'Tp-1', 'Tp0', 'Tp1', 'Tp2', 'Tp3', 'Tp4', 'Tp5'])
Normal Exit elapsed time: 10.04
```
The `-h` (--help) option will list all available options:
```
pps> ./SMap-Multiprocess-Tp.py -h
usage: SMap-Multiprocess-Tp.py [-h] [-T TPLIST [TPLIST ...]] [-i INPUTFILE]
                               [-d INPUTDATA] [-o OUTPUTFILE] [-E E]
                               [-x EXCLUSIONRADIUS] [-c COLUMN] [-t TARGET] [-l LIB]
                               [-p PRED] [-th THETA] [-e] [-C CORES] [-P]

SMap multiprocess Tp

optional arguments:
  -h, --help            show this help message and exit
  -T TPLIST [TPLIST ...], --TpList TPLIST [TPLIST ...]
                        Prediction interval.
  -i INPUTFILE, --inputFile INPUTFILE
                        Input data file.
  -d INPUTDATA, --inputData INPUTDATA
                        Input data frame in sampleData.
  -o OUTPUTFILE, --outputFile OUTPUTFILE
                        Output file.
  -E E, --E E           Embedding dimension E.
  -x EXCLUSIONRADIUS, --exclusionRadius EXCLUSIONRADIUS
                        Exclusion Radius.
  -c COLUMN, --column COLUMN
                        Input file data column name.
  -t TARGET, --target TARGET
                        Input file data target name.
  -l LIB, --lib LIB     lib.
  -p PRED, --pred PRED  pred.
  -th THETA, --theta THETA
                        theta.
  -e, --embedded        embedded flag.
  -C CORES, --cores CORES
                        Multiprocessing cores.
  -P, --plot            Plot results.
```
So to use the dataFile ../../data/LorenzData1000.csv with columns V1, target V2, E = 5, Tp = -3 -2 -1 0 1 2 3 and plot the data:
```
apps> ./SMap-Multiprocess-Tp.py -i ../../data/LorenzData1000.csv -c V1 -t V2 -E 5 -T -3 -2 -1 0 1 2 3 -P
dict_keys(['Tp-3', 'Tp-2', 'Tp-1', 'Tp0', 'Tp1', 'Tp2', 'Tp3'])
```
![Figure_1](https://user-images.githubusercontent.com/6317942/201809136-8b65402e-4678-4c0e-b77a-7a20fe921132.png)
![Figure_2](https://user-images.githubusercontent.com/6317942/201809158-014e6558-c8b1-4416-900e-7de20ea1cb6c.png)

On Windows, it should work the same. But maybe you have to run python and pass the script on the command line as in : `>python SMap-Multiprocess-Tp.py` depending on the shell environment.

Of course, it could be much simpler without the multiprocessing and commnand line interface. You can just cut/paste the needed code and pass in a pandas DataFrame.

**Comment by UhP88** [comment]
Thank you so much for the clarification. it was really helpful to get an idea on the execution.

 I have one small issue about the Compute.Error function. After running the smap function as mentioned in the above code >  pyEDM.ComputeError(results['predictions']['Observations'],results['predictions']['Predictions'] )
and if I run
obs=results['predictions']['Observations']
pred=results['predictions']['Predictions']
PeaersonRes = stats.pearsonr(obs, pred) for the same smap output after removing Nan I get a different pearson correlation coefficient. So I was wondering if compute error function has a different way of computing the rho value.

**Comment by SoftwareLiteracy** [comment]
Perhaps some ideas on this can be gleaned from [Distinguishing time-delayed causal interactions using convergent cross mapping](https://www.nature.com/articles/srep14750) where they look at +-Tp (they call tau) using CCM.  If I understand, negative Tp there are viewed as "interaction delays".  Perhaps +Tp reflects time scales of interaction in the "other direction".  I too would like a good answer to your question ; )
