### ISSUE TITLE
pyEDM install error 2023 Apple M2 Pro running Ventura 

### ISSUE THREAD

**Issue by SoftwareLiteracy** [SugiharaLab/pyEDM#36]
My issue is that on a 2023 Apple M2 Pro running Ventura I get the following error when trying to import pyEDM after install:

```
>>> import pyEDM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexjames/miniconda3/envs/pyedm/lib/python3.10/site-packages/pyEDM/__init__.py", line 5, in <module>
    from pyEDM.CoreEDM import *
  File "/Users/alexjames/miniconda3/envs/pyedm/lib/python3.10/site-packages/pyEDM/CoreEDM.py", line 7, in <module>
    import pyBindEDM
ImportError: dlopen(/Users/alexjames/miniconda3/envs/pyedm/lib/python3.10/site-packages/pyBindEDM.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__Z3SVD9DataFrameIdENSt3__18valarrayIdEE'
```

This is on a fresh conda environment using python 3.10. I’ve tried to do a bit of digging to see what the issue might be but I haven’t had much luck. I came across this [GitHub issue](https://github.com/protocolbuffers/protobuf/issues/10571) which lead to this [stackoverflow thread](https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean) but I wasn’t able to make it much further.

Submitted by Alexander James via email.

**Comment by SoftwareLiteracy** [comment]
If you want to try a manual install, clone or download [pyEDM](https://github.com/SugiharaLab/pyEDM). Then, presuming you have python pip installed, at a console in the pyEDM directory: `python -m pip install . --user`. Or `pip install . --user`.

It also requires LAPACK to be installed.

**Comment by SoftwareLiteracy** [comment]
That seems to have worked! I just had to manually install spicy and force a reinstall of pybind11.

-- Submitted by Alexander James via email.

**Comment by keichi** [comment]
This is likely because `libEDM.a` is built for x86_64 only. The Python extension (`pyBindEDM.cpython-*-darwin.so`) is universal and includes both arm64 and x86_64 binaries, but `libEDM.a` only includes `x86_64 binary, causing symbol resolution to fail at runtime.

Adding `-arch x86_64 -arch arm64` to CFLAGS when building the wheels should fix it.

```
% lipo -archs pyBindEDM.cpython-311-darwin.so
x86_64 arm64
% lipo -extract arm64 -output pyBindEDM.cpython-311-darwin-arm64.so pyBindEDM.cpython-311-darwin.so
% lipo -extract x86_64 -output pyBindEDM.cpython-311-darwin-x86_64.so pyBindEDM.cpython-311-darwin.so
% nm pyBindEDM.cpython-311-darwin-x86_64.so | grep __Z3SVD9DataFrameIdENSt3__18valarrayIdEE
                 0000000000088e80 T __Z3SVD9DataFrameIdENSt3__18valarrayIdEE
% nm pyBindEDM.cpython-311-darwin-arm64.so | grep __Z3SVD9DataFrameIdENSt3__18valarrayIdEE
                 U __Z3SVD9DataFrameIdENSt3__18valarrayIdEE
```

**Comment by SoftwareLiteracy** [comment]
Thanks for the analysis & feedback!

pyEDM wheels are built with MS Azure DevOps Pipelines (https://dev.azure.com/cos0080412/pyEDM). 

The most recent available OSX is macOS 12 Monterey (https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software). 

It seems Ventura is not yet supported.  Is it likely that when Ventura pipeline is provided the build will target the right arch, and that is why a local build on a Ventura machine suceeded? 

Looking around for MS DevOps information, I don't find anything about whether Ventura will be supported.  A blog in 2019 said they will support the last two macOS versions, but Ventura was released in June 2022.

**Comment by keichi** [comment]
macOS binaries are generally backward compatible. So if you build your binary on Monterey, the binary runs on Monterey or later. (You can target an older OS with the `-mmacosx-version-min` compiler flag)

The problem is rather that Apple M2 Pro is an arm64 CPU while Azure DevOps Pipelines (and most other CI services) runs on an x86_64 CPU.

**Comment by SoftwareLiteracy** [comment]
Thanks for pointing this out. 

I'm totally ignorant when it comes to Mac / Windows ; (

pyEDM setup.py has : 
```
class BuildExt( build_ext ):
    
    c_opts = {
        'msvc'    : [],
        'unix'    : ['-llapack'],
        'mingw32' : ['-DMS_WIN64']
    }

    if sys.platform == 'darwin':
        c_opts['unix'] += ['-stdlib=libc++', '-mmacosx-version-min=10.7']

    [...]
```

So perhaps to change ` c_opts['unix'] += ['-stdlib=libc++']` to `c_opts['unix'] += ['-stdlib=libc++', '-arch x86_64', '-arch arm64']` ?
