### ISSUE TITLE
How to deal with the outliers in time series

### ISSUE THREAD

**Issue by wj431364** [SugiharaLab/pyEDM#42]
Hi, i am using the very nice pkg rEDM (pyEDM) in my project. However, i find that function CCM is very sensitive to the outliers in time series, which is mainly from the pearson correlation used in the function.  

In a extreme case, the causality result will drop from 0.7 to 0.1 by only adding a single data point. This is somehow counter-intuitive to the definition of causality.
I want to know if there exists any method i can deal with those outliers. Can i replace the pearson correlation in CCM function with some other metric?

Many thanks!

This is an example to reproduce the issue 
```python
import numpy as np
import pandas as pd
from pyEDM import *
x = np.random.random(200)
y = np.sin(x) + np.random.random(200) * 0.5
x[-1] = 0
data = pd.DataFrame()
data['0'] = 0
data['x1'] = x
data['x2'] = y

E = max(findE(data['x1'].values,data['x2'].values))

CCM(
    dataFrame=data,
    columns='x1',
    target='x2',
    libSizes='50 160 20',
    sample=100,
    E = 3,
    showPlot=True
)


x[-1] = 15
data = pd.DataFrame()
data['0'] = 0
data['x1'] = x
data['x2'] = y

E = max(findE(data['x1'].values,data['x2'].values))

CCM(
    dataFrame=data,
    columns='x1',
    target='x2',
    libSizes='50 160 20',
    sample=100,
    E = 3,
    showPlot=True
)
```
results are 
![image](https://github.com/ha0ye/rEDM/assets/135578169/d7f344d1-510d-4887-9cbe-3660c57630bb)
![image](https://github.com/ha0ye/rEDM/assets/135578169/caf55cb8-8dcf-4fdf-8550-712437afc9b5)

**Comment by wj431364** [comment]
> Thank you for the questions.
> 
> There seem to be multiple questions. One regarding outliers, others regarding the use of EDM and CCM. As with any method, keeping the fundamentals in view is useful. Please consider:
> 
> ### The data
> Prior to application of any method, it is useful to understand the data. The data appear to be essentially noise: ![Figure_1_data-1](https://user-images.githubusercontent.com/6317942/254951916-f4ae7cf7-34ec-4406-9b15-b12215498e63.png)
> 
> Not just noise, but correlated noise:
> 
> ```python
> >>> np.corrcoef( x, y )[0,1]
> 0.8567666985369206
> ```
> 
> ### Identify low dimensional dynamics
> We presume the `FindE()` function takes the first step of identifying an appropriate embedding dimension, Here is the `EmbedDimension()` result for x :
> 
> ```python
> EmbedDimension(dataFrame=data,columns='x1',target='x1',lib="1 200",pred="1 200")
> ```
> 
> ![Figure_2_Edim-x-x](https://user-images.githubusercontent.com/6317942/254952533-49bfb064-8e4a-4f18-892e-80cf9bf46e29.png)
> 
> It appears there is essentially no predictability of the variable x1, which is consistent with it being noise, not a low-dimensional dynamical system.
> 
> Similar result for cross mapping from `x1` to `x2`
> 
> ```python
> EmbedDimension(dataFrame=data,columns='x1',target='x2',lib="1 200",pred="1 200")
> ```
> 
> ![Figure_3_Edim-x-y](https://user-images.githubusercontent.com/6317942/254953111-818e9346-342b-4d07-9165-6c1abcc6bf10.png)
> 
> At this point, there is little utility moving forward with an EDM analysis.
> 
> ### Ill-posed analysis
> Nonetheless, let us proceed for illustrative purposes. Even though we understand application of `CCM` here is not warranted, we find the result:
> 
> ```python
> CCM( dataFrame=data, columns='x1', target='x2',
>            libSizes='50 160 20', sample=100, E = 3, showPlot=True )
> ```
> 
> ![Figure_4_CCM-x1-y1](https://user-images.githubusercontent.com/6317942/254954306-28cafd73-82dd-4dfc-bed8-5a415800e7cf.png)
> 
> Suggesting that cross mapping noise with correlated noise indicates similar "dynamics" in the two time series. You may recall that CCM has three criteria to infer causal influence:
> 
> 1. Cross mapping values indicate shared dynamics
> 2. Convergence of prediction skill as the library of state vectors provides improved representation of the dynamics.
> 3. Rejection of a null hypothesis that random states could produce the inferred causal link.
> 
> This is well-discussed in the literature and demos, vis: [CCM](https://en.wikipedia.org/wiki/Convergent_cross_mapping), [rEDM vignette](https://cran.r-project.org/web/packages/rEDM/vignettes/rEDM-tutorial.pdf), [Sugihara et al (2012)](https://science.sciencemag.org/content/338/6106/496).
> 
> Here, we have evidence of the first criteria (keeping in mind we know this is an ill-posed application since the data do not represent low-dimensional dynamics). Regarding the second criteria: _convergence_ there is no evidence. At this point, there is no support to evaluate the third criteria.
> 
> ### Second data
> ![Figure_5_data-2](https://user-images.githubusercontent.com/6317942/254957971-d8f994cc-a080-4ab1-af2a-2712a8a3d326.png)
> 
> ![Figure_6_Edim-x2-x2](https://user-images.githubusercontent.com/6317942/254958117-ad2f5905-a203-4d19-b4d0-bde2f9d8d86c.png)
> 
> Again, there is no support for the notion the data represent a low dimensional dynamical system.
> 
> Even so, to continue:
> 
> ![Figure_8_CCM-x2-y1](https://user-images.githubusercontent.com/6317942/254958767-a8024b9e-28b5-43cb-98d1-feb9384806b6.png)
> 
> While the cross mapping from `x2:x1` suggests no shared dynamics, which is consistent with the state space of the time series including the large "outlier" being different from the other noise; it is still an ill-posed analysis as there is no evidence of low-dimensional dynamics and the three CCM criteria are not satisfied.

Many thanks!

In your reply, you mentioned " no evidence of low-dimensional dynamics". I understand it is the rejection of causality, even though it will show a convergence behavior if we set the library size from 10. 

However, the causality is defined as one variable drives another, which is just the case in my example. Why we can reject the causality in the two variables as it intuitively satisfies our definition?

Besides, if we reject the causality, does this mean that we will reject causality between any two variables, as long as their causal correlation is noise sensitive?

**Comment by SoftwareLiteracy** [comment]
Well, regarding the correlated noise example, one would not say anything about inference of causality using CCM, except that the test is not applicable. The system is not one of low-dimensional dynamics. "no evidence of low-dimensional dynamics" is not acceptance or rejection of causal inference. The test does not apply. 

The system then suggested is a partial sin wave pair, with very little dynamical structure.  In that example, or any data, it is not enough to simply look at cross map skill and infer causal influence.  The three criteria for CCM need to be satisfied, not just the first one.  The literature provided is clear about this.  

The literature also gives examples dealing with synchronization, periodic components, which can lead one to incorrectly infer if not handled properly.  There is also the potential for serial correlation (autocorrelation in the linear sense) to give inflated cross map values if one is not aware it is the autocorrelation being modeled. This is the purpose for the exclusion radius. 

Review and reflection on the literature addressing these issues will be helpful. 

Hope this helps.
