### ISSUE TITLE
Question about change the prediction skill

### ISSUE THREAD

**Issue by wj431364** [SugiharaLab/pyEDM#43]
Hi, many thanks for such a powerful pkg. I am intensively using EDM in my project, and the pkg is very helpful. 

However, i found that for my real data (which is assumed to have a non-linear dynamics structure), the Pearson correlation is sensitive to some data point, even it looks like a usual point. When i add / remove such a data point, the prediction skill will reduce significantly, although showing evident convergence behavior. 

I try to modify the metric of prediction skill (use Spearman's rank correlation), but I do not how to implement this modification in the pyEDM pkg.
1. is there any method i can change the metric, except modifying the underlying c++ code?
2. if not, is there any method i can store the sample data and compute the corresponding metric manually?

Many thanks!

**Comment by SoftwareLiteracy** [comment]
It should be easy to use any metric you devise. In EDM the function that computes rho has a python wrapper `ComputeError()` that takes two vectors and returns the MAE, Pearson rho, RMSE.

```python
from pyEDM import *
S = Simplex( dataFrame = sampleData["block_3sp"], 
             lib = "1 99", pred = "100 195",  E = 3, 
             columns="x_t y_t z_t", target="x_t" )
ComputeError( S['Observations'], S['Predictions'] )
{'MAE': 0.46600755238547836, 'RMSE': 0.5773576624006942, 'rho': 0.7025808535306135}
```
Since the data (Observations) and predictions are returned from `Simplex`, `SMap` etc., one could use pandas DataFrame corr method:
```python
S[ ['Observations', 'Predictions' ] ].corr()
              Observations  Predictions
Observations      1.000000     0.702581
Predictions       0.702581     1.000000
```

Or, externally using numpy:

```python
from numpy import corrcoef
corrcoef( S['Observations'], S['Predictions' ] )
array([[ 1., nan],
       [nan, nan]])
```

Oh right, there are nan in the returned result from the prediction interval Tp = 1, so ignore the first row:

```python
corrcoef( S['Observations'][1:], S['Predictions' ][1:] )
array([[1.        , 0.70258085],
       [0.70258085, 1.        ]])
```

Here's a function that takes the data, pred and returns the MAE:

```python
def MAE( data, pred ):
     diff = data - pred
     mae = diff.abs().mean()
     return mae

MAE( S['Observations'], S['Predictions' ] )
0.4660075523854783
```
You can devise a similar function to return your desired metric.

**Comment by wj431364** [comment]
> It should be easy to use any metric you devise. In EDM the function that computes rho has a python wrapper `ComputeError()` that takes two vectors and returns the MAE, Pearson rho, RMSE.
> 
> ```python
> from pyEDM import *
> S = Simplex( dataFrame = sampleData["block_3sp"], 
>              lib = "1 99", pred = "100 195",  E = 3, 
>              columns="x_t y_t z_t", target="x_t" )
> ComputeError( S['Observations'], S['Predictions'] )
> {'MAE': 0.46600755238547836, 'RMSE': 0.5773576624006942, 'rho': 0.7025808535306135}
> ```
> 
> Since the data (Observations) and predictions are returned from `Simplex`, `SMap` etc., one could use pandas DataFrame corr method:
> 
> ```python
> S[ ['Observations', 'Predictions' ] ].corr()
>               Observations  Predictions
> Observations      1.000000     0.702581
> Predictions       0.702581     1.000000
> ```
> 
> Or, externally using numpy:
> 
> ```python
> from numpy import corrcoef
> corrcoef( S['Observations'], S['Predictions' ] )
> array([[ 1., nan],
>        [nan, nan]])
> ```
> 
> Oh right, there are nan in the returned result from the prediction interval Tp = 1, so ignore the first row:
> 
> ```python
> corrcoef( S['Observations'][1:], S['Predictions' ][1:] )
> array([[1.        , 0.70258085],
>        [0.70258085, 1.        ]])
> ```
> 
> Here's a function that takes the data, pred and returns the MAE:
> 
> ```python
> def MAE( data, pred ):
>      diff = data - pred
>      mae = diff.abs().mean()
>      return mae
> 
> MAE( S['Observations'], S['Predictions' ] )
> 0.4660075523854783
> ```
> 
> You can devise a similar function to return your desired metric.

Yeah, thanks for your reply. 

Sorry for the misleading, I want to change the prediction skill of CCM function. As it does not return the sample data and the prediction, i do not know how to change the metric.

**Comment by SoftwareLiteracy** [comment]
Ah, I see: `CCM`. 

You are right, `CCM` does not return the actual predictions, but statistics on them. 

If there is a single data point that radically changes a CCM model, perhaps the data or implementation of CCM parameters are not well posed. That should be able to be assessed with `Simplex` since CCM is a statistic on Simplex predictions.
