### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by Atticusl** [SugiharaLab/pyEDM#46]
I have run this code,
'pip install pyEDM',
and got
'Installing collected packages: pyEDM
Successfully installed pyEDM-1.15.0.4'.
Then I want to import this package,
'import pyEDM',
and I got
'Traceback (most recent call last):
  File "...\test_for_ppyEDM\test1_20231025.py", line 1, in <module>
    import pyEDM
  File "...\Lib\site-packages\pyEDM\__init__.py", line 5, in <module>
    from pyEDM.CoreEDM import *
  File "...\Lib\site-packages\pyEDM\CoreEDM.py", line 7, in <module> 
    import pyBindEDM
ImportError: DLL load failed while importing pyBindEDM: 找不到指定的模块。'
I didn't find 'pyBindEDM.py' in folder ‘pyEDM’ and its subfolders. 
I have uninstalled and reinstalled 'pyEDM', but it didn't work.
How can I fix this issue?

**Comment by SoftwareLiteracy** [comment]
On Windows there is currently an issue with pyEDM version 1.15 preventing installation. 

Please use version 1.14.3 : pip install pyEDM==1.14.3.0

**Comment by Atticusl** [comment]
The problem has been solved. Thank you!

**Comment by SoftwareLiteracy** [comment]
Please note version 1.15.1 should install on Windows.

**Comment by aj006600** [comment]
Which version of pyEDM should I download on my m1 macbook? Today, when I tried to reinstall, I found that 'git clone https://github.com/SugiharaLab/pyEDM' doesn't seem to work.

**Comment by SoftwareLiteracy** [comment]
It seems the M1 is an ARM processor. If the usual `pip install pyEDM` does not work, then the wheels (binary installers) for pyEDM are not available. 

You should be able to download the github pyEDM and install manually with `pip install .` in the main pyEDM directory.  This is what you are trying?

**Comment by aj006600** [comment]
I tried following the steps as indicated under 'OSX and Linux' on https://pypi.org/project/pyEDM/

**Comment by aj006600** [comment]
I found the reason; it was because several modules were missing in the new environment. I tried:
"
python3 -m pip install --upgrade pip setuptools wheel
pip install pybind11
"
and it worked successfully. Thank you!!!!

Also, I'd like to know if 1.15.1 is already a perfect version, or if it is advisable to revert to 1.14.3.0?
