### ISSUE TITLE
pyEDM vs rEDM rho values

### ISSUE THREAD

**Issue by zclandry** [SugiharaLab/pyEDM#5]
Hello,
I have been trying to switch some analysis scripts from rEDM (https://ha0ye.github.io/rEDM/articles/rEDM.html) to pyEDM.  I noticed that using the same data I am getting much lower rho values with pyEDM than with rEDM.  Do you have any idea why this might be?  
Thank you for any help.

**Comment by nonlinearnature** [comment]
Can you post an example of where you are finding this discrepancy?

**Comment by SoftwareLiteracy** [comment]
Please note the versions you are comparing. 
    
    The version of rEDM you seem to be referencing is from Dr. Ye's
    personal github.  I am unsure what changes have been made there in
    relation to 0.7.2 which is a version we often compare to.  
    
    Generally, we do not expect equivalence for a number of reasons. 
    Some to do with stochasticity (if random = True), some to do with
    the fact that pyEDM strictly forbids partial data (embedding)
    vectors, and, forbids forecasting beyond the library domain, the
    neighbor tie implementation is a bit different...
    
    If you are using rEDM 1.5.0, and pyEDM 1.5.0.0, then we expect (non
    stochastic) equivalence. 
    
    Thanks.
    

    On 7/20/20 7:20 AM, zclandry wrote:
    
    
      
      Hello,
        I have been trying to switch some analysis scripts from rEDM (https://ha0ye.github.io/rEDM/articles/rEDM.html)
        to pyEDM. I noticed that using the same data I am getting much
        lower rho values with pyEDM than with rEDM. Do you have any idea
        why this might be?
        Thank you for any help.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SugiharaLab/pyEDM/issues/5",
"url": "https://github.com/SugiharaLab/pyEDM/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
