### ISSUE TITLE
Is there a funciton in pyEDM to test the significance of the Pearson correlation coefficients get by CCM?

### ISSUE THREAD

**Issue by yyw2wyy** [SugiharaLab/pyEDM#57]

**Comment by SoftwareLiteracy** [comment]
No, there is not a function to estimate significance. 

In some instances this can be done by evaluating random realizations of the dynamics and comparing CCM correlation of the random surrogates to that of the observed data.  The `SurrogateData` function described in the pdf [docs](https://github.com/SugiharaLab/pyEDM/blob/master/doc/pyEDM.pdf) may be helpful.

An example is shown here:
[Thrips-pyEDM-2.0 - Jupyter Notebook.pdf](https://github.com/user-attachments/files/16426441/Thrips-pyEDM-2.0.-.Jupyter.Notebook.pdf)

Data:
[Thrips.csv.zip](https://github.com/user-attachments/files/16426485/Thrips.csv.zip)

**Comment by yyw2wyy** [comment]
Thank you!
