### ISSUE TITLE
Question about choosing parameters in extended CCM

### ISSUE THREAD

**Issue by yuse2001** [SugiharaLab/pyEDM#58]
Hi, thank you very much for providing such a powerful Python library. I am currently using the CCM method provided by the library to implement ECCM for calculating the time lag between two time series. However, I am encountering some issues with parameter selection.

1. In the real data I am using, each sequence has a different `𝐸`(embedding dimension) as measured by EmbedDimension. However, the CCM calculation requires a single `𝐸` as input. Currently, I am using the larger `𝐸` from the two sequences as input. However, the paper "[Detection of time delays and directional interactions based on time series from complex dynamical systems](url)" points out that when 𝐸 exceeds the optimal `𝐸`, the corresponding `𝑇𝑝`(time lag) at the maximum value in ECCM may shift.This has been quite troubling for me because I want to obtain the correct `𝑇𝑝` . I am wondering if it would be possible to run CCM twice using the optimal `𝐸` for each sequence separately and then combine the two results. For example, if `𝐸 = 3` for `𝑥` and `𝐸 = 6` for `𝑦`, I could run CCM twice, extracting `𝑦 xmap 𝑥` from the results with `𝐸 = 3` since the variable to estimate is `𝑥`, and extracting `𝑥 xmap 𝑦` from the results with `𝐸 = 6`, as it uses `𝑦's` `𝐸`.This approach could potentially avoid the shift in `𝑇𝑝` , but it seems to deviate from the original design of CCM.

2.  The choice of `tau` also has a significant impact on the results of ECCM. I’m unsure whether to set `tau = 1` or to use the mutual information method to select it. I’ve seen literature where `tau` is set to 1, and also cases where it is not. However, in the paper "[Distinguishing time-delayed causal interactions using convergent cross mapping](https://www.nature.com/articles/srep14750)," it is mentioned that if the time series is not oversampled, `tau` should be set to 1. In the discussion in questions [#38](https://github.com/SugiharaLab/pyEDM/issues/38) and [#39](https://github.com/SugiharaLab/pyEDM/issues/39), there are some points raised, but it seems that ECCM is not specifically addressed.
 
3. For CCM results, it is necessary to assess whether they have converged, but it seems there is currently no unified standard for this judgment. Although for a small amount of data, visual inspection can be used, this is not feasible for large datasets. Is there any consideration of adding this feature to pyEDM?
 
4. Is it possible for the `CCM` function to export the results of each sampling calculation? This could be helpful for subsequent calculations and analysis.

I sincerely hope these questions can be answered.

Thanks!

**Comment by SoftwareLiteracy** [comment]
Hi Yuse, 

Thank you for using pyEDM.  Please consider these responses.

1. The short answer is yes, although one needs a separate invocation of CCM for different E as you suggest.  CCM cross maps the `target` variable with an E-dimensional time delay embedding of `columns`.  It does this in both directions by swapping `column` and `target`, but that is just a convenience presuming both variables are part of the same dynamical system. If you are cross mapping variables with different dimensions, you may ask whether or not they belong to the same dynamical system. CCM presumes they are, lack of coupling/convergence indicates they are not. In any case, CCM applies the time delay embedding to the `columns` variable, so one could call CCM twice comparing the `columns:target` output from each run. Regarding E being too large if the same E is used for both, it is generally not a problem to have a few extra dimensions. Of course, this can change the time window contained in each state vector which may be relevant for specific data. 

3. Please note that `tau = 1` is not a time delay, but a time advance. The default value of `tau = -1` is a one time step delay. The paper you cite requires careful reading, as their cross map lag (l) corresponds to `Tp`. However, the point that `tau =  -1` is a reasonable default is fair. To go a bit deeper each time delay vector will contain temporal information spanning |(E-1)*tau|. As E increases the temporal span increases, so there is a tradeoff between `E`:`tau` in representing time scales. In practice, people search for optimal `[E,tau]` combinations to best represent the dynamics depending on the data/problem, but `tau=-1` with an appropriate `E` is a good starting point. 

5. Agreed. There is not a generally accepted criterion for valid convergence, this is an open problem. A flat rho(L) curve is clearly not evidence of convergence. The typical curve behaves as rho(L) = 1 - exp( -a L ).  I have used fits to this curve (value of a) as a criteria. Another approach is to normalize the rho(L) curve over L, then compute a linear slope, setting a threshold for positive slope above which one considers convergence valid. 

7. Yes, this is mentioned in the [docs](https://sugiharalab.github.io/EDM_Documentation/ccm_/) with the `includeData = True` parameter.  For example:

```python
from pyEDM import *
df = sampleData['Lorenz5D']

ccm = CCM( df, columns = 'V5', target = 'V1', libSizes = [50, 100, 900, 950],
           sample = 30, E = 5, includeData = True )

ccm.keys()
dict_keys(['LibMeans', 'PredictStats1', 'PredictStats2'])
>>> 
ccm['LibMeans']
   LibSize     V5:V1     V1:V5
0       50  0.816719  0.573797
1      100  0.866328  0.655912
2      900  0.915085  0.783897
3      950  0.915729  0.813999

ccm['PredictStats1']
    LibSize      rho       MAE     RMSE
0        50  0.85078   8.85334  1.94234
1        50  0.82947   8.84524  2.07176
2        50  0.84164   7.34692  2.00461
3        50  0.84179  10.72683  1.99809
4        50  0.79261   7.50930  2.26578
..      ...      ...       ...      ...
25      950  0.91527   8.66947  1.47492
26      950  0.91649   8.17551  1.46450
27      950  0.91657   8.66947  1.46444
28      950  0.91618   8.66947  1.46706
29      950  0.91600   8.66947  1.46985

[120 rows x 4 columns]

```

**Comment by yuse2001** [comment]
Thank you very much for your response. Due to my lack of experience, I did not use accurate terminology in Question 2, which led to some confusion. However, your answer perfectly reflects the question I originally intended to express. Thank you again for your clarification.
