### ISSUE TITLE
Predictions outside of dataframe

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#6]
Is it possible to make predictions that exceed the number of rows in your dataframe?

**Comment by SoftwareLiteracy** [comment]
Predictions require a state-space point to predict from.  So EDM
    can't make a prediction from an unknown state. 
    
    However, one can predict a time horizon beyond the last available
    data row.  
    
    Here's an example predicting Tp = 3 points beyond the last data row
    (row 198, time 200):
    
    import pyEDM
      s = pyEDM.Simplex( dataFrame =
        pyEDM.sampleData["block_3sp"], lib = "1 99", pred = "190 198", 
        E = 3, columns = "x_t", target = "x_t", Tp = 3)
      
      s
         time  Observations  Predictions  Pred_Variance
      0   192      0.896599          NaN            NaN
      1   193     -0.759573          NaN            NaN
      2   194      0.784424          NaN            NaN
      3   195     -1.277411    -0.528782       0.177785
      4   196      0.558733     0.493894       0.123687
      5   197      0.633977    -0.686964       0.808972
      6   198      0.020644     0.830772       0.011421
      7   199      0.548923    -0.942971       0.147329
      8   200      0.040304    -0.507137       0.527193
      9   201           NaN     0.725564       0.002732
      10  202           NaN    -0.798969       0.052452
      11  203           NaN     1.081306       0.025287
      
      Note that the time value is not the same as the 0-offset row
      number. 
      
    pyEDM.sampleData["block_3sp"].tail(3)
           time       x_t     x_t-1     x_t-2       y_t    
        y_t-1     y_t-2       z_t     z_t-1     z_t-2
      195   198  0.020644  0.633977  0.558733  0.631287 
        0.434703 -0.862808  1.323193  0.358857 -1.153702
      196   199  0.548923  0.020644  0.633977  0.156251 
        0.631287  0.434703 -0.332346  1.323193  0.358857
      197   200  0.040304  0.548923  0.020644 -0.204529 
        0.156251  0.631287  1.615405 -0.332346  1.323193
    
    On 8/7/20 1:59 PM, pshankinclarke
      wrote:
    
    
      
      Is it possible to make predictions that exceed the number of
        rows in your dataframe?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SugiharaLab/pyEDM/issues/6",
"url": "https://github.com/SugiharaLab/pyEDM/issues/6",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pshankinclarke** [comment]
Thank you so much for clarification!
