### ISSUE TITLE
How to set time lag param in Multiview function

### ISSUE THREAD

**Issue by nyanko-box** [SugiharaLab/pyEDM#8]
I could not find time lag parameter in pyEDM.Multiview() at neither function nor parameter documents.
* https://sugiharalab.github.io/EDM_Documentation/edm_functions/
* https://sugiharalab.github.io/EDM_Documentation/parameters/

How can we change time lag to calculate multiviews?

Thanks in advance.

**Comment by nyanko-box** [comment]
@SoftwareLiteracy 

Thank you for replying.

\---
My understanding for the behavior of Multiview() is the following.

All combinations for the number of _**E**_-dimensional variables with _**l**_ lags for each _**n**_ variables are calculated in Multiview().
Then, the top-k views are selected to forecast.

The number of all combination **_m_** = (**_nl_**, **_E_**) - (**_n_**(**_l_**-1), **_E_**)

The parameters are referred in [this paper](https://science.sciencemag.org/content/353/6302/922).
\---

When I consider the combinations for the number of 5-dimensional embedding with the 4 lags for each 7 variables,
Parameter: tau = 4 (= _**l**_) ?

**Comment by SoftwareLiteracy** [comment]
Thank you for pointing this out.  The documentation needs to be
    improved. 
    
    I find the expression in the Science paper difficult to follow since
    the number of lags and embedding dimension E are normally
    related.  An E-dimensional Takens embedding will have E-1 lags
    created, for a total of E dimensions for each variable.  tau itself
    is not really pertinent, since it does not change the dimensionality
    or number of embedding columns (combinations), but specifies the
    time offset used in the E-dimensional embedding.  So no, tau is not
    equal to l. 
    
    This lead to introduction of the parameter D in Multiview so the
    user can independently specify the number of variables used to
    create each evaluated embedding (D), and, the embedding dimension E
    of each variable. 
    
    The best representation is expressed in the API documentation on
    page 11:
    pyEDM/pyEDM.pdf
      at master · SugiharaLab/pyEDM
    
    D represents the number of variables to combine for each
      assessment, if not specified, it is the number of columns.
    
    E is the embedding dimension of each variable. If E = 1, no
      time delay embedding is done.
    
    multiview is the number of top-ranked D-dimensional
      predictions to "average" for the final prediction. Corresponds to
      parameter k in Ye & Sugihara with default k = sqrt(C) where C
      is the number of combinations C(n,D) available from the (n)
      embedding columns taken D at-a-time.
      
    In the case of the Multiview example in pyEDM.Examples(), D = 3
    (columns = "x_t y_t z_t"), E = 3 dimensional embedding of each
    column (adding 2 lags).  n = total number of columns in embedding =
    D*E = 9 and C(n,D) = C(9,3) = 84, m = floor( sqrt(84) ) = 9.
    
    In relation to the Science paper, the expression would be m = C(
    n(l+1), E ) where n = 3 variable, l = 2 lags per variable and E = 3.
    
    
    
    
    On 8/23/20 9:59 PM, nyanko-box wrote:
    
    
      
      ---
        My understanding for the behavior of Multiview() is the
        following.
      All combinations for the number of E-dimensional
        variables with l lags for each n
        variables are calculated in Multiview().
        Then, the top-k views are selected to forecast.
      The number of all combination m = (nl,
        E) - (n(l-1),
        E)
      The parameters are referred in this paper.
        ---
      When I consider the combinations for the number of
        5-dimensional embedding with the 4 lags for each 7 variables,
        Parameter: tau = 4 (= l) ?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SugiharaLab/pyEDM/issues/8#issuecomment-678865047",
"url": "https://github.com/SugiharaLab/pyEDM/issues/8#issuecomment-678865047",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nyanko-box** [comment]
@SoftwareLiteracy 

Thank you for explaining in detail.

I understood:
* the difference between the **_l_** and tau,
* the roles of parameters D, E, and multiview.

Thank you again for your time.
